// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessGrant = `-- name: CreateAccessGrant :one
INSERT INTO access_grants (user_id, plan, festival_id, valid_until, granted_by, promo_code_id, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, plan, festival_id, valid_until, granted_by, promo_code_id, note, revoked_at, created_at
`

type CreateAccessGrantParams struct {
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Plan        string             `db:"plan" json:"plan"`
	FestivalID  pgtype.UUID        `db:"festival_id" json:"festival_id"`
	ValidUntil  pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
	GrantedBy   pgtype.UUID        `db:"granted_by" json:"granted_by"`
	PromoCodeID pgtype.UUID        `db:"promo_code_id" json:"promo_code_id"`
	Note        *string            `db:"note" json:"note"`
}

func (q *Queries) CreateAccessGrant(ctx context.Context, arg CreateAccessGrantParams) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, createAccessGrant,
		arg.UserID,
		arg.Plan,
		arg.FestivalID,
		arg.ValidUntil,
		arg.GrantedBy,
		arg.PromoCodeID,
		arg.Note,
	)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.FestivalID,
		&i.ValidUntil,
		&i.GrantedBy,
		&i.PromoCodeID,
		&i.Note,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (code, plan, duration_days, max_uses, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, plan, duration_days, max_uses, use_count, expires_at, created_by, revoked_at, created_at
`

type CreatePromoCodeParams struct {
	Code         string             `db:"code" json:"code"`
	Plan         string             `db:"plan" json:"plan"`
	DurationDays int32              `db:"duration_days" json:"duration_days"`
	MaxUses      *int32             `db:"max_uses" json:"max_uses"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy    pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromoCode,
		arg.Code,
		arg.Plan,
		arg.DurationDays,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Plan,
		&i.DurationDays,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, plan, duration_days, max_uses, use_count, expires_at, created_by, revoked_at, created_at FROM promo_codes WHERE code = $1
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Plan,
		&i.DurationDays,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPromoCodeByID = `-- name: GetPromoCodeByID :one
SELECT id, code, plan, duration_days, max_uses, use_count, expires_at, created_by, revoked_at, created_at FROM promo_codes WHERE id = $1
`

func (q *Queries) GetPromoCodeByID(ctx context.Context, id pgtype.UUID) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByID, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Plan,
		&i.DurationDays,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveGrant = `-- name: HasActiveGrant :one
SELECT EXISTS (
    SELECT 1 FROM access_grants
    WHERE user_id = $1
      AND plan = $2
      AND revoked_at IS NULL
      AND valid_until > now()
      AND (festival_id IS NULL OR festival_id = $3)
) AS has_grant
`

type HasActiveGrantParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	Plan       string      `db:"plan" json:"plan"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

// $3 (festival_id): pass pgtype.UUID{} for non-festival plans; set for festival_activation checks.
func (q *Queries) HasActiveGrant(ctx context.Context, arg HasActiveGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveGrant, arg.UserID, arg.Plan, arg.FestivalID)
	var has_grant bool
	err := row.Scan(&has_grant)
	return has_grant, err
}

const hasRedeemedPromo = `-- name: HasRedeemedPromo :one
SELECT EXISTS (
    SELECT 1 FROM access_grants
    WHERE user_id = $1 AND promo_code_id = $2
) AS has_redeemed
`

type HasRedeemedPromoParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	PromoCodeID pgtype.UUID `db:"promo_code_id" json:"promo_code_id"`
}

func (q *Queries) HasRedeemedPromo(ctx context.Context, arg HasRedeemedPromoParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRedeemedPromo, arg.UserID, arg.PromoCodeID)
	var has_redeemed bool
	err := row.Scan(&has_redeemed)
	return has_redeemed, err
}

const incrementPromoUseCount = `-- name: IncrementPromoUseCount :one
UPDATE promo_codes
SET use_count = use_count + 1
WHERE id = $1
  AND (max_uses IS NULL OR use_count < max_uses)
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, code, plan, duration_days, max_uses, use_count, expires_at, created_by, revoked_at, created_at
`

func (q *Queries) IncrementPromoUseCount(ctx context.Context, id pgtype.UUID) (PromoCode, error) {
	row := q.db.QueryRow(ctx, incrementPromoUseCount, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Plan,
		&i.DurationDays,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGrants = `-- name: ListActiveGrants :many
SELECT id, user_id, plan, festival_id, valid_until, granted_by, promo_code_id, note, revoked_at, created_at FROM access_grants
WHERE user_id = $1 AND revoked_at IS NULL AND valid_until > now()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveGrants(ctx context.Context, userID pgtype.UUID) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, listActiveGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.FestivalID,
			&i.ValidUntil,
			&i.GrantedBy,
			&i.PromoCodeID,
			&i.Note,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT id, code, plan, duration_days, max_uses, use_count, expires_at, created_by, revoked_at, created_at FROM promo_codes ORDER BY created_at DESC
`

func (q *Queries) ListPromoCodes(ctx context.Context) ([]PromoCode, error) {
	rows, err := q.db.Query(ctx, listPromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoCode
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Plan,
			&i.DurationDays,
			&i.MaxUses,
			&i.UseCount,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, is_admin, mfa_enabled, created_at
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListUsersParams struct {
	Email string `db:"email" json:"email"`
	Off   int32  `db:"off" json:"off"`
	Lim   int32  `db:"lim" json:"lim"`
}

type ListUsersRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Email      string             `db:"email" json:"email"`
	IsAdmin    bool               `db:"is_admin" json:"is_admin"`
	MfaEnabled bool               `db:"mfa_enabled" json:"mfa_enabled"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Email, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsAdmin,
			&i.MfaEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessGrant = `-- name: RevokeAccessGrant :exec
UPDATE access_grants
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAccessGrant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAccessGrant, id)
	return err
}

const revokePromoCode = `-- name: RevokePromoCode :exec
UPDATE promo_codes
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePromoCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokePromoCode, id)
	return err
}
