// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubmittedUndecidedByFestival = `-- name: CountSubmittedUndecidedByFestival :one
SELECT COUNT(*)::int AS count
FROM applications a
JOIN application_forms f ON a.form_id = f.id
WHERE f.festival_id = $1
  AND a.decision = 'undecided'
`

// Applications still needing a decision (block release while > 0).
func (q *Queries) CountSubmittedUndecidedByFestival(ctx context.Context, festivalID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSubmittedUndecidedByFestival, festivalID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (form_id, artist_id, answers)
VALUES ($1, $2, $3)
RETURNING id, form_id, artist_id, answers, created_at, updated_at, rank, shortlisted, review_flag, decision, released_at
`

type CreateApplicationParams struct {
	FormID   pgtype.UUID     `db:"form_id" json:"form_id"`
	ArtistID pgtype.UUID     `db:"artist_id" json:"artist_id"`
	Answers  json.RawMessage `db:"answers" json:"answers"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.FormID, arg.ArtistID, arg.Answers)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rank,
		&i.Shortlisted,
		&i.ReviewFlag,
		&i.Decision,
		&i.ReleasedAt,
	)
	return i, err
}

const getApplicationByFormAndArtist = `-- name: GetApplicationByFormAndArtist :one
SELECT id, form_id, artist_id, answers, created_at, updated_at, rank, shortlisted, review_flag, decision, released_at FROM applications WHERE form_id = $1 AND artist_id = $2
`

type GetApplicationByFormAndArtistParams struct {
	FormID   pgtype.UUID `db:"form_id" json:"form_id"`
	ArtistID pgtype.UUID `db:"artist_id" json:"artist_id"`
}

func (q *Queries) GetApplicationByFormAndArtist(ctx context.Context, arg GetApplicationByFormAndArtistParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByFormAndArtist, arg.FormID, arg.ArtistID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rank,
		&i.Shortlisted,
		&i.ReviewFlag,
		&i.Decision,
		&i.ReleasedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, form_id, artist_id, answers, created_at, updated_at, rank, shortlisted, review_flag, decision, released_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rank,
		&i.Shortlisted,
		&i.ReviewFlag,
		&i.Decision,
		&i.ReleasedAt,
	)
	return i, err
}

const listApplicationsByArtist = `-- name: ListApplicationsByArtist :many
SELECT id, form_id, artist_id, answers, created_at, updated_at, rank, shortlisted, review_flag, decision, released_at FROM applications WHERE artist_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByArtist(ctx context.Context, artistID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.Shortlisted,
			&i.ReviewFlag,
			&i.Decision,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByForm = `-- name: ListApplicationsByForm :many
SELECT id, form_id, artist_id, answers, created_at, updated_at, rank, shortlisted, review_flag, decision, released_at FROM applications WHERE form_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListApplicationsByForm(ctx context.Context, formID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.Shortlisted,
			&i.ReviewFlag,
			&i.Decision,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByFormWithArtist = `-- name: ListApplicationsByFormWithArtist :many
SELECT
  a.id,
  a.form_id,
  a.artist_id,
  a.decision,
  a.released_at,
  a.rank,
  a.shortlisted,
  a.review_flag,
  a.answers,
  a.created_at,
  a.updated_at,
  ap.display_name,
  ap.avatar_s3_key,
  ap.medium_tags,
  ap.location_label,
  ap.social_links,
  ap.bio,
  ap.support_url
FROM applications a
JOIN artist_profiles ap ON ap.id = a.artist_id
WHERE a.form_id = $1
ORDER BY a.rank ASC, a.created_at ASC
`

type ListApplicationsByFormWithArtistRow struct {
	ID            pgtype.UUID         `db:"id" json:"id"`
	FormID        pgtype.UUID         `db:"form_id" json:"form_id"`
	ArtistID      pgtype.UUID         `db:"artist_id" json:"artist_id"`
	Decision      ApplicationDecision `db:"decision" json:"decision"`
	ReleasedAt    pgtype.Timestamptz  `db:"released_at" json:"released_at"`
	Rank          int32               `db:"rank" json:"rank"`
	Shortlisted   bool                `db:"shortlisted" json:"shortlisted"`
	ReviewFlag    bool                `db:"review_flag" json:"review_flag"`
	Answers       json.RawMessage     `db:"answers" json:"answers"`
	CreatedAt     pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	DisplayName   string              `db:"display_name" json:"display_name"`
	AvatarS3Key   *string             `db:"avatar_s3_key" json:"avatar_s3_key"`
	MediumTags    []string            `db:"medium_tags" json:"medium_tags"`
	LocationLabel *string             `db:"location_label" json:"location_label"`
	SocialLinks   json.RawMessage     `db:"social_links" json:"social_links"`
	Bio           string              `db:"bio" json:"bio"`
	SupportUrl    *string             `db:"support_url" json:"support_url"`
}

func (q *Queries) ListApplicationsByFormWithArtist(ctx context.Context, formID pgtype.UUID) ([]ListApplicationsByFormWithArtistRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByFormWithArtist, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByFormWithArtistRow
	for rows.Next() {
		var i ListApplicationsByFormWithArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Decision,
			&i.ReleasedAt,
			&i.Rank,
			&i.Shortlisted,
			&i.ReviewFlag,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarS3Key,
			&i.MediumTags,
			&i.LocationLabel,
			&i.SocialLinks,
			&i.Bio,
			&i.SupportUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByFormWithArtistExcludingReviewer = `-- name: ListApplicationsByFormWithArtistExcludingReviewer :many
SELECT a.id, a.form_id, a.artist_id, a.decision, a.released_at, a.rank, a.shortlisted,
  a.review_flag, a.answers, a.created_at, a.updated_at,
  ap.display_name, ap.avatar_s3_key, ap.medium_tags, ap.location_label,
  ap.social_links, ap.bio, ap.support_url
FROM applications a
JOIN artist_profiles ap ON ap.id = a.artist_id
WHERE a.form_id = $1
  AND ap.user_id IS DISTINCT FROM $2
ORDER BY a.rank ASC, a.created_at ASC
`

type ListApplicationsByFormWithArtistExcludingReviewerParams struct {
	FormID pgtype.UUID `db:"form_id" json:"form_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type ListApplicationsByFormWithArtistExcludingReviewerRow struct {
	ID            pgtype.UUID         `db:"id" json:"id"`
	FormID        pgtype.UUID         `db:"form_id" json:"form_id"`
	ArtistID      pgtype.UUID         `db:"artist_id" json:"artist_id"`
	Decision      ApplicationDecision `db:"decision" json:"decision"`
	ReleasedAt    pgtype.Timestamptz  `db:"released_at" json:"released_at"`
	Rank          int32               `db:"rank" json:"rank"`
	Shortlisted   bool                `db:"shortlisted" json:"shortlisted"`
	ReviewFlag    bool                `db:"review_flag" json:"review_flag"`
	Answers       json.RawMessage     `db:"answers" json:"answers"`
	CreatedAt     pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	DisplayName   string              `db:"display_name" json:"display_name"`
	AvatarS3Key   *string             `db:"avatar_s3_key" json:"avatar_s3_key"`
	MediumTags    []string            `db:"medium_tags" json:"medium_tags"`
	LocationLabel *string             `db:"location_label" json:"location_label"`
	SocialLinks   json.RawMessage     `db:"social_links" json:"social_links"`
	Bio           string              `db:"bio" json:"bio"`
	SupportUrl    *string             `db:"support_url" json:"support_url"`
}

// Reviewer-scoped: hides the application belonging to the reviewer ($2 = user_id).
func (q *Queries) ListApplicationsByFormWithArtistExcludingReviewer(ctx context.Context, arg ListApplicationsByFormWithArtistExcludingReviewerParams) ([]ListApplicationsByFormWithArtistExcludingReviewerRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByFormWithArtistExcludingReviewer, arg.FormID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByFormWithArtistExcludingReviewerRow
	for rows.Next() {
		var i ListApplicationsByFormWithArtistExcludingReviewerRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Decision,
			&i.ReleasedAt,
			&i.Rank,
			&i.Shortlisted,
			&i.ReviewFlag,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarS3Key,
			&i.MediumTags,
			&i.LocationLabel,
			&i.SocialLinks,
			&i.Bio,
			&i.SupportUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedApplicationsByFestival = `-- name: ListStagedApplicationsByFestival :many
SELECT a.id, a.form_id, a.artist_id, a.answers, a.created_at, a.updated_at, a.rank, a.shortlisted, a.review_flag, a.decision, a.released_at
FROM applications a
JOIN application_forms f ON a.form_id = f.id
WHERE f.festival_id = $1
  AND a.decision <> 'undecided'
  AND a.released_at IS NULL
`

func (q *Queries) ListStagedApplicationsByFestival(ctx context.Context, festivalID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listStagedApplicationsByFestival, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.Shortlisted,
			&i.ReviewFlag,
			&i.Decision,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDecisionsForFestival = `-- name: ReleaseDecisionsForFestival :many
UPDATE applications a
SET released_at = now(), updated_at = now()
FROM application_forms f
WHERE a.form_id = f.id
  AND f.festival_id = $1
  AND a.decision <> 'undecided'
  AND a.released_at IS NULL
RETURNING a.id, a.form_id, a.artist_id, a.decision, a.released_at
`

type ReleaseDecisionsForFestivalRow struct {
	ID         pgtype.UUID         `db:"id" json:"id"`
	FormID     pgtype.UUID         `db:"form_id" json:"form_id"`
	ArtistID   pgtype.UUID         `db:"artist_id" json:"artist_id"`
	Decision   ApplicationDecision `db:"decision" json:"decision"`
	ReleasedAt pgtype.Timestamptz  `db:"released_at" json:"released_at"`
}

// Publish every decided-but-unreleased application in the festival. Returns the
// rows it just released so the handler can create lineup rows / clear spots / email.
func (q *Queries) ReleaseDecisionsForFestival(ctx context.Context, festivalID pgtype.UUID) ([]ReleaseDecisionsForFestivalRow, error) {
	rows, err := q.db.Query(ctx, releaseDecisionsForFestival, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseDecisionsForFestivalRow
	for rows.Next() {
		var i ReleaseDecisionsForFestivalRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Decision,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationFlags = `-- name: UpdateApplicationFlags :one
UPDATE applications
SET shortlisted = $2, review_flag = $3, decision = $4, updated_at = now()
WHERE id = $1
RETURNING id, form_id, artist_id, answers, created_at, updated_at, rank, shortlisted, review_flag, decision, released_at
`

type UpdateApplicationFlagsParams struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	Shortlisted bool                `db:"shortlisted" json:"shortlisted"`
	ReviewFlag  bool                `db:"review_flag" json:"review_flag"`
	Decision    ApplicationDecision `db:"decision" json:"decision"`
}

func (q *Queries) UpdateApplicationFlags(ctx context.Context, arg UpdateApplicationFlagsParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationFlags,
		arg.ID,
		arg.Shortlisted,
		arg.ReviewFlag,
		arg.Decision,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rank,
		&i.Shortlisted,
		&i.ReviewFlag,
		&i.Decision,
		&i.ReleasedAt,
	)
	return i, err
}

const updateApplicationRank = `-- name: UpdateApplicationRank :exec
UPDATE applications SET rank = $1, updated_at = now() WHERE id = $2
`

type UpdateApplicationRankParams struct {
	Rank int32       `db:"rank" json:"rank"`
	ID   pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateApplicationRank(ctx context.Context, arg UpdateApplicationRankParams) error {
	_, err := q.db.Exec(ctx, updateApplicationRank, arg.Rank, arg.ID)
	return err
}
