// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_notes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationNote = `-- name: CreateApplicationNote :one
INSERT INTO application_notes (application_id, content)
VALUES ($1, $2)
RETURNING id, application_id, content, created_at
`

type CreateApplicationNoteParams struct {
	ApplicationID pgtype.UUID `db:"application_id" json:"application_id"`
	Content       string      `db:"content" json:"content"`
}

func (q *Queries) CreateApplicationNote(ctx context.Context, arg CreateApplicationNoteParams) (ApplicationNote, error) {
	row := q.db.QueryRow(ctx, createApplicationNote, arg.ApplicationID, arg.Content)
	var i ApplicationNote
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listNotesByApplications = `-- name: ListNotesByApplications :many
SELECT id, application_id, content, created_at FROM application_notes
WHERE application_id = ANY($1::uuid[])
ORDER BY application_id, created_at ASC
`

func (q *Queries) ListNotesByApplications(ctx context.Context, dollar_1 []pgtype.UUID) ([]ApplicationNote, error) {
	rows, err := q.db.Query(ctx, listNotesByApplications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationNote
	for rows.Next() {
		var i ApplicationNote
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
