// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_scores.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMyScore = `-- name: GetMyScore :one
SELECT score FROM application_scores WHERE application_id = $1 AND reviewer_id = $2
`

type GetMyScoreParams struct {
	ApplicationID pgtype.UUID `db:"application_id" json:"application_id"`
	ReviewerID    pgtype.UUID `db:"reviewer_id" json:"reviewer_id"`
}

func (q *Queries) GetMyScore(ctx context.Context, arg GetMyScoreParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMyScore, arg.ApplicationID, arg.ReviewerID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const scoreSummaryByApplications = `-- name: ScoreSummaryByApplications :many
SELECT application_id, AVG(score)::float8 AS avg_score, COUNT(*)::int AS score_count
FROM application_scores
WHERE application_id = ANY($1::uuid[])
GROUP BY application_id
`

type ScoreSummaryByApplicationsRow struct {
	ApplicationID pgtype.UUID `db:"application_id" json:"application_id"`
	AvgScore      float64     `db:"avg_score" json:"avg_score"`
	ScoreCount    int32       `db:"score_count" json:"score_count"`
}

func (q *Queries) ScoreSummaryByApplications(ctx context.Context, dollar_1 []pgtype.UUID) ([]ScoreSummaryByApplicationsRow, error) {
	rows, err := q.db.Query(ctx, scoreSummaryByApplications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoreSummaryByApplicationsRow
	for rows.Next() {
		var i ScoreSummaryByApplicationsRow
		if err := rows.Scan(&i.ApplicationID, &i.AvgScore, &i.ScoreCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplicationScore = `-- name: UpsertApplicationScore :one
INSERT INTO application_scores (application_id, reviewer_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (application_id, reviewer_id)
DO UPDATE SET score = EXCLUDED.score, updated_at = now()
RETURNING application_id, reviewer_id, score, updated_at
`

type UpsertApplicationScoreParams struct {
	ApplicationID pgtype.UUID `db:"application_id" json:"application_id"`
	ReviewerID    pgtype.UUID `db:"reviewer_id" json:"reviewer_id"`
	Score         int32       `db:"score" json:"score"`
}

func (q *Queries) UpsertApplicationScore(ctx context.Context, arg UpsertApplicationScoreParams) (ApplicationScore, error) {
	row := q.db.QueryRow(ctx, upsertApplicationScore, arg.ApplicationID, arg.ReviewerID, arg.Score)
	var i ApplicationScore
	err := row.Scan(
		&i.ApplicationID,
		&i.ReviewerID,
		&i.Score,
		&i.UpdatedAt,
	)
	return i, err
}
