// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (form_id, artist_id, answers)
VALUES ($1, $2, $3)
RETURNING id, form_id, artist_id, status, answers, created_at, updated_at
`

type CreateApplicationParams struct {
	FormID   pgtype.UUID     `db:"form_id" json:"form_id"`
	ArtistID pgtype.UUID     `db:"artist_id" json:"artist_id"`
	Answers  json.RawMessage `db:"answers" json:"answers"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.FormID, arg.ArtistID, arg.Answers)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Status,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByFormAndArtist = `-- name: GetApplicationByFormAndArtist :one
SELECT id, form_id, artist_id, status, answers, created_at, updated_at FROM applications WHERE form_id = $1 AND artist_id = $2
`

type GetApplicationByFormAndArtistParams struct {
	FormID   pgtype.UUID `db:"form_id" json:"form_id"`
	ArtistID pgtype.UUID `db:"artist_id" json:"artist_id"`
}

func (q *Queries) GetApplicationByFormAndArtist(ctx context.Context, arg GetApplicationByFormAndArtistParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByFormAndArtist, arg.FormID, arg.ArtistID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Status,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, form_id, artist_id, status, answers, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Status,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsByArtist = `-- name: ListApplicationsByArtist :many
SELECT id, form_id, artist_id, status, answers, created_at, updated_at FROM applications WHERE artist_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByArtist(ctx context.Context, artistID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Status,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByForm = `-- name: ListApplicationsByForm :many
SELECT id, form_id, artist_id, status, answers, created_at, updated_at FROM applications WHERE form_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListApplicationsByForm(ctx context.Context, formID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ArtistID,
			&i.Status,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, form_id, artist_id, status, answers, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	ID     pgtype.UUID       `db:"id" json:"id"`
	Status ApplicationStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus, arg.ID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ArtistID,
		&i.Status,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
