// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_forms.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApplicationFormByFestivalID = `-- name: GetApplicationFormByFestivalID :one
SELECT id, festival_id, fields, open_at, close_at, max_applications, created_at, updated_at FROM application_forms WHERE festival_id = $1
`

func (q *Queries) GetApplicationFormByFestivalID(ctx context.Context, festivalID pgtype.UUID) (ApplicationForm, error) {
	row := q.db.QueryRow(ctx, getApplicationFormByFestivalID, festivalID)
	var i ApplicationForm
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Fields,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxApplications,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApplicationForm = `-- name: UpsertApplicationForm :one
INSERT INTO application_forms (festival_id, fields, open_at, close_at, max_applications)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (festival_id) DO UPDATE
    SET fields           = EXCLUDED.fields,
        open_at          = EXCLUDED.open_at,
        close_at         = EXCLUDED.close_at,
        max_applications = EXCLUDED.max_applications,
        updated_at       = now()
RETURNING id, festival_id, fields, open_at, close_at, max_applications, created_at, updated_at
`

type UpsertApplicationFormParams struct {
	FestivalID      pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Fields          json.RawMessage    `db:"fields" json:"fields"`
	OpenAt          pgtype.Timestamptz `db:"open_at" json:"open_at"`
	CloseAt         pgtype.Timestamptz `db:"close_at" json:"close_at"`
	MaxApplications *int32             `db:"max_applications" json:"max_applications"`
}

func (q *Queries) UpsertApplicationForm(ctx context.Context, arg UpsertApplicationFormParams) (ApplicationForm, error) {
	row := q.db.QueryRow(ctx, upsertApplicationForm,
		arg.FestivalID,
		arg.Fields,
		arg.OpenAt,
		arg.CloseAt,
		arg.MaxApplications,
	)
	var i ApplicationForm
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Fields,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxApplications,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
