// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist_profiles.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicProfiles = `-- name: CountPublicProfiles :one
SELECT COUNT(*) FROM artist_profiles
WHERE visibility = 'public'
`

func (q *Queries) CountPublicProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtistProfile = `-- name: CreateArtistProfile :one
INSERT INTO artist_profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token
`

type CreateArtistProfileParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) CreateArtistProfile(ctx context.Context, arg CreateArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, createArtistProfile, arg.UserID, arg.DisplayName)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
	)
	return i, err
}

const getArtistProfileByID = `-- name: GetArtistProfileByID :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token FROM artist_profiles WHERE id = $1
`

func (q *Queries) GetArtistProfileByID(ctx context.Context, id pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByID, id)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
	)
	return i, err
}

const getArtistProfileByPreviewToken = `-- name: GetArtistProfileByPreviewToken :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token FROM artist_profiles WHERE preview_token = $1
`

func (q *Queries) GetArtistProfileByPreviewToken(ctx context.Context, previewToken string) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByPreviewToken, previewToken)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
	)
	return i, err
}

const getArtistProfileByUserID = `-- name: GetArtistProfileByUserID :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token FROM artist_profiles WHERE user_id = $1
`

func (q *Queries) GetArtistProfileByUserID(ctx context.Context, userID pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByUserID, userID)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
	)
	return i, err
}

const listPublicProfiles = `-- name: ListPublicProfiles :many
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token FROM artist_profiles
WHERE visibility = 'public'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicProfilesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicProfiles(ctx context.Context, arg ListPublicProfilesParams) ([]ArtistProfile, error) {
	rows, err := q.db.Query(ctx, listPublicProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistProfile
	for rows.Next() {
		var i ArtistProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Bio,
			&i.LocationLabel,
			&i.ShowLocation,
			&i.MediumTags,
			&i.SocialLinks,
			&i.AvatarS3Key,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadlineImageUrls,
			&i.Visibility,
			&i.PreviewToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateArtistProfilePreviewToken = `-- name: RotateArtistProfilePreviewToken :one
UPDATE artist_profiles
SET preview_token = replace(gen_random_uuid()::text, '-', ''),
    updated_at    = now()
WHERE user_id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token
`

func (q *Queries) RotateArtistProfilePreviewToken(ctx context.Context, userID pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, rotateArtistProfilePreviewToken, userID)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
	)
	return i, err
}

const updateArtistProfile = `-- name: UpdateArtistProfile :one
UPDATE artist_profiles
SET display_name        = $2,
    bio                 = $3,
    location_label      = $4,
    show_location       = $5,
    medium_tags         = $6,
    social_links        = $7,
    avatar_s3_key       = $8,
    headline_image_urls = $9,
    visibility          = $10,
    updated_at          = now()
WHERE id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token
`

type UpdateArtistProfileParams struct {
	ID                pgtype.UUID     `db:"id" json:"id"`
	DisplayName       string          `db:"display_name" json:"display_name"`
	Bio               string          `db:"bio" json:"bio"`
	LocationLabel     *string         `db:"location_label" json:"location_label"`
	ShowLocation      bool            `db:"show_location" json:"show_location"`
	MediumTags        []string        `db:"medium_tags" json:"medium_tags"`
	SocialLinks       json.RawMessage `db:"social_links" json:"social_links"`
	AvatarS3Key       *string         `db:"avatar_s3_key" json:"avatar_s3_key"`
	HeadlineImageUrls []string        `db:"headline_image_urls" json:"headline_image_urls"`
	Visibility        string          `db:"visibility" json:"visibility"`
}

func (q *Queries) UpdateArtistProfile(ctx context.Context, arg UpdateArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, updateArtistProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.LocationLabel,
		arg.ShowLocation,
		arg.MediumTags,
		arg.SocialLinks,
		arg.AvatarS3Key,
		arg.HeadlineImageUrls,
		arg.Visibility,
	)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
	)
	return i, err
}
