// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist_profiles.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimArtistProfile = `-- name: ClaimArtistProfile :one
UPDATE artist_profiles
SET user_id            = $1,
    claimed_at         = now(),
    setup_completed_at = now(),
    updated_at         = now()
WHERE claim_token = $2
  AND user_id IS NULL
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

type ClaimArtistProfileParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	ClaimToken *string     `db:"claim_token" json:"claim_token"`
}

// Atomically binds a profile to a user. Returns no row if already claimed
// (user_id IS NOT NULL) or if the token doesn't exist — caller checks for
// pgx.ErrNoRows and returns 409. Stamps setup_completed_at so the claimer
// lands on the editor, not the first-run wizard (the page was pre-built).
func (q *Queries) ClaimArtistProfile(ctx context.Context, arg ClaimArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, claimArtistProfile, arg.UserID, arg.ClaimToken)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const completeArtistProfileSetup = `-- name: CompleteArtistProfileSetup :one
UPDATE artist_profiles
SET setup_completed_at = COALESCE(setup_completed_at, now()),
    updated_at         = now()
WHERE user_id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

// Idempotently marks first-run setup complete. COALESCE keeps the first
// completion timestamp if called more than once, and always returns the row.
func (q *Queries) CompleteArtistProfileSetup(ctx context.Context, userID pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, completeArtistProfileSetup, userID)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const countPublicProfiles = `-- name: CountPublicProfiles :one
SELECT COUNT(*) FROM artist_profiles
WHERE visibility = 'public'
`

func (q *Queries) CountPublicProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtistProfile = `-- name: CreateArtistProfile :one
INSERT INTO artist_profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

type CreateArtistProfileParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) CreateArtistProfile(ctx context.Context, arg CreateArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, createArtistProfile, arg.UserID, arg.DisplayName)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const createProspectProfile = `-- name: CreateProspectProfile :one
INSERT INTO artist_profiles (display_name, bio, location_label, medium_tags, social_links, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

type CreateProspectProfileParams struct {
	DisplayName   string          `db:"display_name" json:"display_name"`
	Bio           string          `db:"bio" json:"bio"`
	LocationLabel *string         `db:"location_label" json:"location_label"`
	MediumTags    []string        `db:"medium_tags" json:"medium_tags"`
	SocialLinks   json.RawMessage `db:"social_links" json:"social_links"`
	CreatedBy     pgtype.UUID     `db:"created_by" json:"created_by"`
}

// Creates an unclaimed prospect profile (user_id NULL) seeded from admin data.
func (q *Queries) CreateProspectProfile(ctx context.Context, arg CreateProspectProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, createProspectProfile,
		arg.DisplayName,
		arg.Bio,
		arg.LocationLabel,
		arg.MediumTags,
		arg.SocialLinks,
		arg.CreatedBy,
	)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const getArtistProfileByClaimToken = `-- name: GetArtistProfileByClaimToken :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes FROM artist_profiles WHERE claim_token = $1
`

func (q *Queries) GetArtistProfileByClaimToken(ctx context.Context, claimToken *string) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByClaimToken, claimToken)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const getArtistProfileByID = `-- name: GetArtistProfileByID :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes FROM artist_profiles WHERE id = $1
`

func (q *Queries) GetArtistProfileByID(ctx context.Context, id pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByID, id)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const getArtistProfileByPreviewToken = `-- name: GetArtistProfileByPreviewToken :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes FROM artist_profiles WHERE preview_token = $1
`

func (q *Queries) GetArtistProfileByPreviewToken(ctx context.Context, previewToken string) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByPreviewToken, previewToken)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const getArtistProfileByUserID = `-- name: GetArtistProfileByUserID :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes FROM artist_profiles WHERE user_id = $1
`

func (q *Queries) GetArtistProfileByUserID(ctx context.Context, userID pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByUserID, userID)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const getProspectByNameAndCreator = `-- name: GetProspectByNameAndCreator :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes FROM artist_profiles
WHERE display_name = $1
  AND created_by   = $2
  AND user_id IS NULL
LIMIT 1
`

type GetProspectByNameAndCreatorParams struct {
	DisplayName string      `db:"display_name" json:"display_name"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"created_by"`
}

// Idempotency check: return an existing unclaimed prospect by name + admin creator.
func (q *Queries) GetProspectByNameAndCreator(ctx context.Context, arg GetProspectByNameAndCreatorParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getProspectByNameAndCreator, arg.DisplayName, arg.CreatedBy)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const getSpotHistoryForProfile = `-- name: GetSpotHistoryForProfile :many
SELECT
    fs.id               AS spot_id,
    fs.lat,
    fs.lng,
    fs.mural_status,
    f.id                AS festival_id,
    f.name              AS festival_name,
    COALESCE(EXTRACT(YEAR FROM f.start_date)::int, 0) AS festival_year
FROM festival_spots fs
JOIN festivals f ON f.id = fs.festival_id
WHERE fs.artist_id = $1
  AND f.deleted_at IS NULL
  AND f.status IN ('live', 'closed')
ORDER BY f.start_date DESC NULLS LAST
`

type GetSpotHistoryForProfileRow struct {
	SpotID       pgtype.UUID    `db:"spot_id" json:"spot_id"`
	Lat          pgtype.Numeric `db:"lat" json:"lat"`
	Lng          pgtype.Numeric `db:"lng" json:"lng"`
	MuralStatus  string         `db:"mural_status" json:"mural_status"`
	FestivalID   pgtype.UUID    `db:"festival_id" json:"festival_id"`
	FestivalName string         `db:"festival_name" json:"festival_name"`
	FestivalYear interface{}    `db:"festival_year" json:"festival_year"`
}

// Returns festival spot placements for a given artist profile.
// Only includes spots from live or closed festivals (not draft/open).
func (q *Queries) GetSpotHistoryForProfile(ctx context.Context, artistID pgtype.UUID) ([]GetSpotHistoryForProfileRow, error) {
	rows, err := q.db.Query(ctx, getSpotHistoryForProfile, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotHistoryForProfileRow
	for rows.Next() {
		var i GetSpotHistoryForProfileRow
		if err := rows.Scan(
			&i.SpotID,
			&i.Lat,
			&i.Lng,
			&i.MuralStatus,
			&i.FestivalID,
			&i.FestivalName,
			&i.FestivalYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProfiles = `-- name: ListPublicProfiles :many
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes FROM artist_profiles
WHERE visibility = 'public'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicProfilesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicProfiles(ctx context.Context, arg ListPublicProfilesParams) ([]ArtistProfile, error) {
	rows, err := q.db.Query(ctx, listPublicProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistProfile
	for rows.Next() {
		var i ArtistProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Bio,
			&i.LocationLabel,
			&i.ShowLocation,
			&i.MediumTags,
			&i.SocialLinks,
			&i.AvatarS3Key,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadlineImageUrls,
			&i.Visibility,
			&i.PreviewToken,
			&i.ClaimToken,
			&i.ClaimedAt,
			&i.CreatedBy,
			&i.SupportUrl,
			&i.SetupCompletedAt,
			&i.HasUnpublishedChanges,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateArtistProfilePreviewToken = `-- name: RotateArtistProfilePreviewToken :one
UPDATE artist_profiles
SET preview_token = replace(gen_random_uuid()::text, '-', ''),
    updated_at    = now()
WHERE user_id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

func (q *Queries) RotateArtistProfilePreviewToken(ctx context.Context, userID pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, rotateArtistProfilePreviewToken, userID)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const setArtistProfileVisibility = `-- name: SetArtistProfileVisibility :one
UPDATE artist_profiles
SET visibility = $2,
    updated_at = now()
WHERE user_id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

type SetArtistProfileVisibilityParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	Visibility string      `db:"visibility" json:"visibility"`
}

func (q *Queries) SetArtistProfileVisibility(ctx context.Context, arg SetArtistProfileVisibilityParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, setArtistProfileVisibility, arg.UserID, arg.Visibility)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const setProspectClaimToken = `-- name: SetProspectClaimToken :one
UPDATE artist_profiles
SET claim_token = $2,
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

type SetProspectClaimTokenParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ClaimToken *string     `db:"claim_token" json:"claim_token"`
}

// Sets a unique claim token on a prospect profile. Called during prospect creation.
func (q *Queries) SetProspectClaimToken(ctx context.Context, arg SetProspectClaimTokenParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, setProspectClaimToken, arg.ID, arg.ClaimToken)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}

const updateArtistProfile = `-- name: UpdateArtistProfile :one
UPDATE artist_profiles
SET display_name        = $2,
    bio                 = $3,
    location_label      = $4,
    show_location       = $5,
    medium_tags         = $6,
    social_links        = $7,
    avatar_s3_key       = $8,
    headline_image_urls = $9,
    visibility          = $10,
    support_url         = $11,
    updated_at          = now()
WHERE id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at, headline_image_urls, visibility, preview_token, claim_token, claimed_at, created_by, support_url, setup_completed_at, has_unpublished_changes
`

type UpdateArtistProfileParams struct {
	ID                pgtype.UUID     `db:"id" json:"id"`
	DisplayName       string          `db:"display_name" json:"display_name"`
	Bio               string          `db:"bio" json:"bio"`
	LocationLabel     *string         `db:"location_label" json:"location_label"`
	ShowLocation      bool            `db:"show_location" json:"show_location"`
	MediumTags        []string        `db:"medium_tags" json:"medium_tags"`
	SocialLinks       json.RawMessage `db:"social_links" json:"social_links"`
	AvatarS3Key       *string         `db:"avatar_s3_key" json:"avatar_s3_key"`
	HeadlineImageUrls []string        `db:"headline_image_urls" json:"headline_image_urls"`
	Visibility        string          `db:"visibility" json:"visibility"`
	SupportUrl        *string         `db:"support_url" json:"support_url"`
}

func (q *Queries) UpdateArtistProfile(ctx context.Context, arg UpdateArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, updateArtistProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.LocationLabel,
		arg.ShowLocation,
		arg.MediumTags,
		arg.SocialLinks,
		arg.AvatarS3Key,
		arg.HeadlineImageUrls,
		arg.Visibility,
		arg.SupportUrl,
	)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlineImageUrls,
		&i.Visibility,
		&i.PreviewToken,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedBy,
		&i.SupportUrl,
		&i.SetupCompletedAt,
		&i.HasUnpublishedChanges,
	)
	return i, err
}
