// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist_profiles.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtistProfile = `-- name: CreateArtistProfile :one
INSERT INTO artist_profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at
`

type CreateArtistProfileParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) CreateArtistProfile(ctx context.Context, arg CreateArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, createArtistProfile, arg.UserID, arg.DisplayName)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistProfileByID = `-- name: GetArtistProfileByID :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at FROM artist_profiles WHERE id = $1
`

func (q *Queries) GetArtistProfileByID(ctx context.Context, id pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByID, id)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistProfileByUserID = `-- name: GetArtistProfileByUserID :one
SELECT id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at FROM artist_profiles WHERE user_id = $1
`

func (q *Queries) GetArtistProfileByUserID(ctx context.Context, userID pgtype.UUID) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, getArtistProfileByUserID, userID)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtistProfile = `-- name: UpdateArtistProfile :one
UPDATE artist_profiles
SET display_name   = $2,
    bio            = $3,
    location_label = $4,
    show_location  = $5,
    medium_tags    = $6,
    social_links   = $7,
    avatar_s3_key  = $8,
    updated_at     = now()
WHERE id = $1
RETURNING id, user_id, display_name, bio, location_label, show_location, medium_tags, social_links, avatar_s3_key, created_at, updated_at
`

type UpdateArtistProfileParams struct {
	ID            pgtype.UUID     `db:"id" json:"id"`
	DisplayName   string          `db:"display_name" json:"display_name"`
	Bio           string          `db:"bio" json:"bio"`
	LocationLabel *string         `db:"location_label" json:"location_label"`
	ShowLocation  bool            `db:"show_location" json:"show_location"`
	MediumTags    []string        `db:"medium_tags" json:"medium_tags"`
	SocialLinks   json.RawMessage `db:"social_links" json:"social_links"`
	AvatarS3Key   *string         `db:"avatar_s3_key" json:"avatar_s3_key"`
}

func (q *Queries) UpdateArtistProfile(ctx context.Context, arg UpdateArtistProfileParams) (ArtistProfile, error) {
	row := q.db.QueryRow(ctx, updateArtistProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.LocationLabel,
		arg.ShowLocation,
		arg.MediumTags,
		arg.SocialLinks,
		arg.AvatarS3Key,
	)
	var i ArtistProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.LocationLabel,
		&i.ShowLocation,
		&i.MediumTags,
		&i.SocialLinks,
		&i.AvatarS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
