// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beta.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBetaInvitesByCreator = `-- name: CountBetaInvitesByCreator :one
SELECT COUNT(*)::int FROM beta_invites WHERE created_by = $1
`

func (q *Queries) CountBetaInvitesByCreator(ctx context.Context, createdBy pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBetaInvitesByCreator, createdBy)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBetaFeedback = `-- name: CreateBetaFeedback :one
INSERT INTO beta_feedback (user_id, kind, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, kind, body, admin_note, created_at
`

type CreateBetaFeedbackParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Kind   string      `db:"kind" json:"kind"`
	Body   string      `db:"body" json:"body"`
}

func (q *Queries) CreateBetaFeedback(ctx context.Context, arg CreateBetaFeedbackParams) (BetaFeedback, error) {
	row := q.db.QueryRow(ctx, createBetaFeedback, arg.UserID, arg.Kind, arg.Body)
	var i BetaFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Body,
		&i.AdminNote,
		&i.CreatedAt,
	)
	return i, err
}

const createBetaInvite = `-- name: CreateBetaInvite :one
INSERT INTO beta_invites (code, created_by, max_uses, cohort, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, created_by, max_uses, used_count, cohort, expires_at, created_at
`

type CreateBetaInviteParams struct {
	Code      string             `db:"code" json:"code"`
	CreatedBy pgtype.UUID        `db:"created_by" json:"created_by"`
	MaxUses   int32              `db:"max_uses" json:"max_uses"`
	Cohort    string             `db:"cohort" json:"cohort"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateBetaInvite(ctx context.Context, arg CreateBetaInviteParams) (BetaInvite, error) {
	row := q.db.QueryRow(ctx, createBetaInvite,
		arg.Code,
		arg.CreatedBy,
		arg.MaxUses,
		arg.Cohort,
		arg.ExpiresAt,
	)
	var i BetaInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UsedCount,
		&i.Cohort,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createBetaUser = `-- name: CreateBetaUser :one
INSERT INTO users (email, password_hash, is_beta, beta_cohort, invited_by, invited_via)
VALUES ($1, $2, true, $3, $4, $5)
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin, is_beta, beta_cohort, invited_by, invited_via
`

type CreateBetaUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
	BetaCohort   *string     `db:"beta_cohort" json:"beta_cohort"`
	InvitedBy    pgtype.UUID `db:"invited_by" json:"invited_by"`
	InvitedVia   pgtype.UUID `db:"invited_via" json:"invited_via"`
}

// Creates a user with is_beta=true and invite provenance fields set.
// Use inside the beta-invite-gated signup transaction (see auth/signup.go).
func (q *Queries) CreateBetaUser(ctx context.Context, arg CreateBetaUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createBetaUser,
		arg.Email,
		arg.PasswordHash,
		arg.BetaCohort,
		arg.InvitedBy,
		arg.InvitedVia,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
		&i.IsBeta,
		&i.BetaCohort,
		&i.InvitedBy,
		&i.InvitedVia,
	)
	return i, err
}

const getBetaInviteByCode = `-- name: GetBetaInviteByCode :one
SELECT id, code, created_by, max_uses, used_count, cohort, expires_at, created_at FROM beta_invites WHERE code = $1 LIMIT 1
`

func (q *Queries) GetBetaInviteByCode(ctx context.Context, code string) (BetaInvite, error) {
	row := q.db.QueryRow(ctx, getBetaInviteByCode, code)
	var i BetaInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UsedCount,
		&i.Cohort,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBetaFeedback = `-- name: ListAllBetaFeedback :many
SELECT id, user_id, kind, body, admin_note, created_at FROM beta_feedback ORDER BY created_at DESC
`

func (q *Queries) ListAllBetaFeedback(ctx context.Context) ([]BetaFeedback, error) {
	rows, err := q.db.Query(ctx, listAllBetaFeedback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BetaFeedback
	for rows.Next() {
		var i BetaFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Body,
			&i.AdminNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBetaFeedbackByUser = `-- name: ListBetaFeedbackByUser :many
SELECT id, user_id, kind, body, admin_note, created_at FROM beta_feedback WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBetaFeedbackByUser(ctx context.Context, userID pgtype.UUID) ([]BetaFeedback, error) {
	rows, err := q.db.Query(ctx, listBetaFeedbackByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BetaFeedback
	for rows.Next() {
		var i BetaFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Body,
			&i.AdminNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBetaInviteesByInviter = `-- name: ListBetaInviteesByInviter :many
SELECT id, email, beta_cohort, created_at
FROM users
WHERE invited_by = $1
ORDER BY created_at ASC
`

type ListBetaInviteesByInviterRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Email      string             `db:"email" json:"email"`
	BetaCohort *string            `db:"beta_cohort" json:"beta_cohort"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBetaInviteesByInviter(ctx context.Context, invitedBy pgtype.UUID) ([]ListBetaInviteesByInviterRow, error) {
	rows, err := q.db.Query(ctx, listBetaInviteesByInviter, invitedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBetaInviteesByInviterRow
	for rows.Next() {
		var i ListBetaInviteesByInviterRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.BetaCohort,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBetaInvites = `-- name: ListBetaInvites :many
SELECT id, code, created_by, max_uses, used_count, cohort, expires_at, created_at FROM beta_invites ORDER BY created_at DESC
`

func (q *Queries) ListBetaInvites(ctx context.Context) ([]BetaInvite, error) {
	rows, err := q.db.Query(ctx, listBetaInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BetaInvite
	for rows.Next() {
		var i BetaInvite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UsedCount,
			&i.Cohort,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBetaInvitesByCreator = `-- name: ListBetaInvitesByCreator :many
SELECT id, code, created_by, max_uses, used_count, cohort, expires_at, created_at FROM beta_invites WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBetaInvitesByCreator(ctx context.Context, createdBy pgtype.UUID) ([]BetaInvite, error) {
	rows, err := q.db.Query(ctx, listBetaInvitesByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BetaInvite
	for rows.Next() {
		var i BetaInvite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UsedCount,
			&i.Cohort,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemBetaInvite = `-- name: RedeemBetaInvite :one
UPDATE beta_invites
SET used_count = used_count + 1
WHERE code = $1
  AND used_count < max_uses
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, code, created_by, max_uses, used_count, cohort, expires_at, created_at
`

// Atomically increments used_count only when quota not yet exhausted.
// Returns ErrNoRows if code is not found, quota is full, or invite has expired.
// Caller must interpret ErrNoRows as 403 (code invalid or exhausted).
func (q *Queries) RedeemBetaInvite(ctx context.Context, code string) (BetaInvite, error) {
	row := q.db.QueryRow(ctx, redeemBetaInvite, code)
	var i BetaInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UsedCount,
		&i.Cohort,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateBetaFeedbackNote = `-- name: UpdateBetaFeedbackNote :one
UPDATE beta_feedback SET admin_note = $2 WHERE id = $1 RETURNING id, user_id, kind, body, admin_note, created_at
`

type UpdateBetaFeedbackNoteParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	AdminNote *string     `db:"admin_note" json:"admin_note"`
}

func (q *Queries) UpdateBetaFeedbackNote(ctx context.Context, arg UpdateBetaFeedbackNoteParams) (BetaFeedback, error) {
	row := q.db.QueryRow(ctx, updateBetaFeedbackNote, arg.ID, arg.AdminNote)
	var i BetaFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Body,
		&i.AdminNote,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWaitlistRequest = `-- name: UpsertWaitlistRequest :exec
INSERT INTO waitlist_requests (email)
VALUES ($1)
ON CONFLICT (email) DO NOTHING
`

func (q *Queries) UpsertWaitlistRequest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, upsertWaitlistRequest, email)
	return err
}
