// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrgPayment = `-- name: CreateOrgPayment :one
INSERT INTO organiser_payments (user_id, festival_id, stripe_checkout_session_id, charge_type, amount_pence)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, festival_id, stripe_checkout_session_id, stripe_payment_intent_id, charge_type, amount_pence, status, paid_at, created_at
`

type CreateOrgPaymentParams struct {
	UserID                  pgtype.UUID `db:"user_id" json:"user_id"`
	FestivalID              pgtype.UUID `db:"festival_id" json:"festival_id"`
	StripeCheckoutSessionID *string     `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	ChargeType              string      `db:"charge_type" json:"charge_type"`
	AmountPence             int32       `db:"amount_pence" json:"amount_pence"`
}

func (q *Queries) CreateOrgPayment(ctx context.Context, arg CreateOrgPaymentParams) (OrganiserPayment, error) {
	row := q.db.QueryRow(ctx, createOrgPayment,
		arg.UserID,
		arg.FestivalID,
		arg.StripeCheckoutSessionID,
		arg.ChargeType,
		arg.AmountPence,
	)
	var i OrganiserPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FestivalID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ChargeType,
		&i.AmountPence,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, festival_id, stripe_subscription_id, stripe_price_id, plan, billing_interval, status, current_period_end, created_at, updated_at FROM subscriptions
WHERE user_id = $1 AND status = 'active'
  AND (festival_id IS NULL OR festival_id = $2)
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveSubscriptionParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, arg.UserID, arg.FestivalID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FestivalID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.BillingInterval,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFestivalEndDate = `-- name: GetFestivalEndDate :one
SELECT end_date FROM festivals
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetFestivalEndDate(ctx context.Context, id pgtype.UUID) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getFestivalEndDate, id)
	var end_date pgtype.Date
	err := row.Scan(&end_date)
	return end_date, err
}

const getOrgPaymentBySession = `-- name: GetOrgPaymentBySession :one
SELECT id, user_id, festival_id, stripe_checkout_session_id, stripe_payment_intent_id, charge_type, amount_pence, status, paid_at, created_at FROM organiser_payments
WHERE stripe_checkout_session_id = $1
LIMIT 1
`

func (q *Queries) GetOrgPaymentBySession(ctx context.Context, stripeCheckoutSessionID *string) (OrganiserPayment, error) {
	row := q.db.QueryRow(ctx, getOrgPaymentBySession, stripeCheckoutSessionID)
	var i OrganiserPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FestivalID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ChargeType,
		&i.AmountPence,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, user_id, festival_id, stripe_subscription_id, stripe_price_id, plan, billing_interval, status, current_period_end, created_at, updated_at FROM subscriptions
WHERE stripe_subscription_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FestivalID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.BillingInterval,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStripeCustomerID = `-- name: GetUserStripeCustomerID :one
SELECT stripe_customer_id FROM users WHERE id = $1
`

func (q *Queries) GetUserStripeCustomerID(ctx context.Context, id pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getUserStripeCustomerID, id)
	var stripe_customer_id *string
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const hasActiveFestivalActivation = `-- name: HasActiveFestivalActivation :one
SELECT EXISTS (
  SELECT 1 FROM organiser_payments
  WHERE user_id = $1 AND festival_id = $2 AND charge_type = 'festival_activation' AND status = 'paid'
) AS paid
`

type HasActiveFestivalActivationParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

func (q *Queries) HasActiveFestivalActivation(ctx context.Context, arg HasActiveFestivalActivationParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveFestivalActivation, arg.UserID, arg.FestivalID)
	var paid bool
	err := row.Scan(&paid)
	return paid, err
}

const hasPaidSetupFee = `-- name: HasPaidSetupFee :one
SELECT EXISTS (
  SELECT 1 FROM organiser_payments
  WHERE user_id = $1 AND charge_type = 'setup_fee' AND status = 'paid'
) AS paid
`

func (q *Queries) HasPaidSetupFee(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPaidSetupFee, userID)
	var paid bool
	err := row.Scan(&paid)
	return paid, err
}

const markOrgPaymentPaidIfPending = `-- name: MarkOrgPaymentPaidIfPending :one
UPDATE organiser_payments
SET status = 'paid', stripe_payment_intent_id = $2, paid_at = now()
WHERE stripe_checkout_session_id = $1 AND status = 'pending'
RETURNING id, user_id, festival_id, stripe_checkout_session_id, stripe_payment_intent_id, charge_type, amount_pence, status, paid_at, created_at
`

type MarkOrgPaymentPaidIfPendingParams struct {
	StripeCheckoutSessionID *string `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	StripePaymentIntentID   *string `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
}

// Idempotent paid transition: only updates rows in 'pending' state. Returns
// the updated row, or pgx.ErrNoRows if the row was already paid (Stripe retry)
// or no row matches the session id.
func (q *Queries) MarkOrgPaymentPaidIfPending(ctx context.Context, arg MarkOrgPaymentPaidIfPendingParams) (OrganiserPayment, error) {
	row := q.db.QueryRow(ctx, markOrgPaymentPaidIfPending, arg.StripeCheckoutSessionID, arg.StripePaymentIntentID)
	var i OrganiserPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FestivalID,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ChargeType,
		&i.AmountPence,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :exec
UPDATE subscriptions
SET status = $2, updated_at = now()
WHERE stripe_subscription_id = $1
`

type SetSubscriptionStatusParams struct {
	StripeSubscriptionID *string `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	Status               string  `db:"status" json:"status"`
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionStatus, arg.StripeSubscriptionID, arg.Status)
	return err
}

const setUserStripeCustomerID = `-- name: SetUserStripeCustomerID :exec
UPDATE users SET stripe_customer_id = $2 WHERE id = $1
`

type SetUserStripeCustomerIDParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	StripeCustomerID *string     `db:"stripe_customer_id" json:"stripe_customer_id"`
}

func (q *Queries) SetUserStripeCustomerID(ctx context.Context, arg SetUserStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setUserStripeCustomerID, arg.ID, arg.StripeCustomerID)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (user_id, festival_id, stripe_subscription_id, stripe_price_id, plan, billing_interval, status, current_period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (stripe_subscription_id) DO UPDATE
  SET status             = EXCLUDED.status,
      current_period_end = EXCLUDED.current_period_end,
      stripe_price_id    = EXCLUDED.stripe_price_id,
      plan               = EXCLUDED.plan,
      billing_interval   = EXCLUDED.billing_interval,
      updated_at         = now()
RETURNING id, user_id, festival_id, stripe_subscription_id, stripe_price_id, plan, billing_interval, status, current_period_end, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	FestivalID           pgtype.UUID        `db:"festival_id" json:"festival_id"`
	StripeSubscriptionID *string            `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	StripePriceID        string             `db:"stripe_price_id" json:"stripe_price_id"`
	Plan                 string             `db:"plan" json:"plan"`
	BillingInterval      string             `db:"billing_interval" json:"billing_interval"`
	Status               string             `db:"status" json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.FestivalID,
		arg.StripeSubscriptionID,
		arg.StripePriceID,
		arg.Plan,
		arg.BillingInterval,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FestivalID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.BillingInterval,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
