// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection_images.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCollectionImage = `-- name: AttachCollectionImage :one
INSERT INTO collection_images (collection_id, s3_key, cdn_url, display_order)
VALUES ($1, $2, $3, $4)
RETURNING id, collection_id, s3_key, cdn_url, display_order, created_at
`

type AttachCollectionImageParams struct {
	CollectionID pgtype.UUID `db:"collection_id" json:"collection_id"`
	S3Key        string      `db:"s3_key" json:"s3_key"`
	CdnUrl       string      `db:"cdn_url" json:"cdn_url"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
}

func (q *Queries) AttachCollectionImage(ctx context.Context, arg AttachCollectionImageParams) (CollectionImage, error) {
	row := q.db.QueryRow(ctx, attachCollectionImage,
		arg.CollectionID,
		arg.S3Key,
		arg.CdnUrl,
		arg.DisplayOrder,
	)
	var i CollectionImage
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.S3Key,
		&i.CdnUrl,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const countCollectionImages = `-- name: CountCollectionImages :one
SELECT COUNT(*) FROM collection_images WHERE collection_id = $1
`

func (q *Queries) CountCollectionImages(ctx context.Context, collectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectionImages, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCollectionImage = `-- name: DeleteCollectionImage :exec
DELETE FROM collection_images WHERE id = $1
`

func (q *Queries) DeleteCollectionImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionImage, id)
	return err
}

const getCollectionImageByID = `-- name: GetCollectionImageByID :one
SELECT id, collection_id, s3_key, cdn_url, display_order, created_at FROM collection_images WHERE id = $1
`

func (q *Queries) GetCollectionImageByID(ctx context.Context, id pgtype.UUID) (CollectionImage, error) {
	row := q.db.QueryRow(ctx, getCollectionImageByID, id)
	var i CollectionImage
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.S3Key,
		&i.CdnUrl,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectionImages = `-- name: ListCollectionImages :many
SELECT id, collection_id, s3_key, cdn_url, display_order, created_at FROM collection_images
WHERE collection_id = $1
ORDER BY display_order, created_at
`

func (q *Queries) ListCollectionImages(ctx context.Context, collectionID pgtype.UUID) ([]CollectionImage, error) {
	rows, err := q.db.Query(ctx, listCollectionImages, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionImage
	for rows.Next() {
		var i CollectionImage
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.S3Key,
			&i.CdnUrl,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionImageOrder = `-- name: UpdateCollectionImageOrder :exec
UPDATE collection_images SET display_order = $2 WHERE id = $1
`

type UpdateCollectionImageOrderParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
}

func (q *Queries) UpdateCollectionImageOrder(ctx context.Context, arg UpdateCollectionImageOrderParams) error {
	_, err := q.db.Exec(ctx, updateCollectionImageOrder, arg.ID, arg.DisplayOrder)
	return err
}
