// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (artist_profile_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, artist_profile_id, name, description, cover_s3_key, status, display_order, created_at, updated_at
`

type CreateCollectionParams struct {
	ArtistProfileID pgtype.UUID `db:"artist_profile_id" json:"artist_profile_id"`
	Name            string      `db:"name" json:"name"`
	Description     string      `db:"description" json:"description"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.ArtistProfileID, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ArtistProfileID,
		&i.Name,
		&i.Description,
		&i.CoverS3Key,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, artist_profile_id, name, description, cover_s3_key, status, display_order, created_at, updated_at FROM collections WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ArtistProfileID,
		&i.Name,
		&i.Description,
		&i.CoverS3Key,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionsByProfileID = `-- name: ListCollectionsByProfileID :many
SELECT id, artist_profile_id, name, description, cover_s3_key, status, display_order, created_at, updated_at FROM collections
WHERE artist_profile_id = $1
ORDER BY display_order, created_at
`

func (q *Queries) ListCollectionsByProfileID(ctx context.Context, artistProfileID pgtype.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByProfileID, artistProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.ArtistProfileID,
			&i.Name,
			&i.Description,
			&i.CoverS3Key,
			&i.Status,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name         = $2,
    description  = $3,
    cover_s3_key = $4,
    status       = $5,
    updated_at   = now()
WHERE id = $1
RETURNING id, artist_profile_id, name, description, cover_s3_key, status, display_order, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description string           `db:"description" json:"description"`
	CoverS3Key  *string          `db:"cover_s3_key" json:"cover_s3_key"`
	Status      CollectionStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CoverS3Key,
		arg.Status,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ArtistProfileID,
		&i.Name,
		&i.Description,
		&i.CoverS3Key,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCollectionOrder = `-- name: UpdateCollectionOrder :exec
UPDATE collections SET display_order = $2 WHERE id = $1
`

type UpdateCollectionOrderParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
}

func (q *Queries) UpdateCollectionOrder(ctx context.Context, arg UpdateCollectionOrderParams) error {
	_, err := q.db.Exec(ctx, updateCollectionOrder, arg.ID, arg.DisplayOrder)
	return err
}
