// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endorsements.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateEndorsement = `-- name: CreateOrUpdateEndorsement :one
INSERT INTO endorsements (endorser_id, endorsee_id, kind, festival_id, body, skills)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (endorser_id, endorsee_id) DO UPDATE
  SET kind        = EXCLUDED.kind,
      festival_id = EXCLUDED.festival_id,
      body        = EXCLUDED.body,
      skills      = EXCLUDED.skills,
      updated_at  = now()
RETURNING id, endorser_id, endorsee_id, kind, festival_id, body, skills, hidden_by_endorsee, moderation_status, created_at, updated_at
`

type CreateOrUpdateEndorsementParams struct {
	EndorserID pgtype.UUID `db:"endorser_id" json:"endorser_id"`
	EndorseeID pgtype.UUID `db:"endorsee_id" json:"endorsee_id"`
	Kind       string      `db:"kind" json:"kind"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	Body       *string     `db:"body" json:"body"`
	Skills     []string    `db:"skills" json:"skills"`
}

func (q *Queries) CreateOrUpdateEndorsement(ctx context.Context, arg CreateOrUpdateEndorsementParams) (Endorsement, error) {
	row := q.db.QueryRow(ctx, createOrUpdateEndorsement,
		arg.EndorserID,
		arg.EndorseeID,
		arg.Kind,
		arg.FestivalID,
		arg.Body,
		arg.Skills,
	)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.EndorserID,
		&i.EndorseeID,
		&i.Kind,
		&i.FestivalID,
		&i.Body,
		&i.Skills,
		&i.HiddenByEndorsee,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndorsement = `-- name: DeleteEndorsement :exec
DELETE FROM endorsements WHERE id = $1
`

func (q *Queries) DeleteEndorsement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndorsement, id)
	return err
}

const getEndorsementByID = `-- name: GetEndorsementByID :one
SELECT id, endorser_id, endorsee_id, kind, festival_id, body, skills, hidden_by_endorsee, moderation_status, created_at, updated_at FROM endorsements WHERE id = $1
`

func (q *Queries) GetEndorsementByID(ctx context.Context, id pgtype.UUID) (Endorsement, error) {
	row := q.db.QueryRow(ctx, getEndorsementByID, id)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.EndorserID,
		&i.EndorseeID,
		&i.Kind,
		&i.FestivalID,
		&i.Body,
		&i.Skills,
		&i.HiddenByEndorsee,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicEndorsements = `-- name: ListPublicEndorsements :many
SELECT
  e.id,
  e.endorser_id,
  e.endorsee_id,
  e.kind,
  e.festival_id,
  e.body,
  e.skills,
  e.hidden_by_endorsee,
  e.moderation_status,
  e.created_at,
  e.updated_at,
  ap.display_name  AS endorser_display_name,
  ap.avatar_s3_key AS endorser_avatar_s3_key,
  f.name           AS festival_name
FROM endorsements e
LEFT JOIN artist_profiles ap ON ap.user_id = e.endorser_id
LEFT JOIN festivals f ON f.id = e.festival_id
WHERE e.endorsee_id = $1
  AND e.moderation_status = 'ok'
  AND e.hidden_by_endorsee = false
ORDER BY (e.kind = 'organiser') DESC, e.created_at DESC
`

type ListPublicEndorsementsRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	EndorserID          pgtype.UUID        `db:"endorser_id" json:"endorser_id"`
	EndorseeID          pgtype.UUID        `db:"endorsee_id" json:"endorsee_id"`
	Kind                string             `db:"kind" json:"kind"`
	FestivalID          pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Body                *string            `db:"body" json:"body"`
	Skills              []string           `db:"skills" json:"skills"`
	HiddenByEndorsee    bool               `db:"hidden_by_endorsee" json:"hidden_by_endorsee"`
	ModerationStatus    string             `db:"moderation_status" json:"moderation_status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndorserDisplayName *string            `db:"endorser_display_name" json:"endorser_display_name"`
	EndorserAvatarS3Key *string            `db:"endorser_avatar_s3_key" json:"endorser_avatar_s3_key"`
	FestivalName        *string            `db:"festival_name" json:"festival_name"`
}

func (q *Queries) ListPublicEndorsements(ctx context.Context, endorseeID pgtype.UUID) ([]ListPublicEndorsementsRow, error) {
	rows, err := q.db.Query(ctx, listPublicEndorsements, endorseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicEndorsementsRow
	for rows.Next() {
		var i ListPublicEndorsementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EndorserID,
			&i.EndorseeID,
			&i.Kind,
			&i.FestivalID,
			&i.Body,
			&i.Skills,
			&i.HiddenByEndorsee,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndorserDisplayName,
			&i.EndorserAvatarS3Key,
			&i.FestivalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedEndorsements = `-- name: ListReceivedEndorsements :many
SELECT
  e.id,
  e.endorser_id,
  e.endorsee_id,
  e.kind,
  e.festival_id,
  e.body,
  e.skills,
  e.hidden_by_endorsee,
  e.moderation_status,
  e.created_at,
  e.updated_at,
  ap.display_name  AS endorser_display_name,
  ap.avatar_s3_key AS endorser_avatar_s3_key,
  f.name           AS festival_name
FROM endorsements e
LEFT JOIN artist_profiles ap ON ap.user_id = e.endorser_id
LEFT JOIN festivals f ON f.id = e.festival_id
WHERE e.endorsee_id = $1
ORDER BY (e.kind = 'organiser') DESC, e.created_at DESC
`

type ListReceivedEndorsementsRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	EndorserID          pgtype.UUID        `db:"endorser_id" json:"endorser_id"`
	EndorseeID          pgtype.UUID        `db:"endorsee_id" json:"endorsee_id"`
	Kind                string             `db:"kind" json:"kind"`
	FestivalID          pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Body                *string            `db:"body" json:"body"`
	Skills              []string           `db:"skills" json:"skills"`
	HiddenByEndorsee    bool               `db:"hidden_by_endorsee" json:"hidden_by_endorsee"`
	ModerationStatus    string             `db:"moderation_status" json:"moderation_status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndorserDisplayName *string            `db:"endorser_display_name" json:"endorser_display_name"`
	EndorserAvatarS3Key *string            `db:"endorser_avatar_s3_key" json:"endorser_avatar_s3_key"`
	FestivalName        *string            `db:"festival_name" json:"festival_name"`
}

// All endorsements for the authenticated endorsee (includes hidden + moderated).
func (q *Queries) ListReceivedEndorsements(ctx context.Context, endorseeID pgtype.UUID) ([]ListReceivedEndorsementsRow, error) {
	rows, err := q.db.Query(ctx, listReceivedEndorsements, endorseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivedEndorsementsRow
	for rows.Next() {
		var i ListReceivedEndorsementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EndorserID,
			&i.EndorseeID,
			&i.Kind,
			&i.FestivalID,
			&i.Body,
			&i.Skills,
			&i.HiddenByEndorsee,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndorserDisplayName,
			&i.EndorserAvatarS3Key,
			&i.FestivalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEndorsementModerationStatus = `-- name: SetEndorsementModerationStatus :one
UPDATE endorsements
SET moderation_status = $2,
    updated_at        = now()
WHERE id = $1
RETURNING id, endorser_id, endorsee_id, kind, festival_id, body, skills, hidden_by_endorsee, moderation_status, created_at, updated_at
`

type SetEndorsementModerationStatusParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	ModerationStatus string      `db:"moderation_status" json:"moderation_status"`
}

// Called by E17 moderation machinery.
func (q *Queries) SetEndorsementModerationStatus(ctx context.Context, arg SetEndorsementModerationStatusParams) (Endorsement, error) {
	row := q.db.QueryRow(ctx, setEndorsementModerationStatus, arg.ID, arg.ModerationStatus)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.EndorserID,
		&i.EndorseeID,
		&i.Kind,
		&i.FestivalID,
		&i.Body,
		&i.Skills,
		&i.HiddenByEndorsee,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEndorsementVisibility = `-- name: SetEndorsementVisibility :one
UPDATE endorsements
SET hidden_by_endorsee = $2,
    updated_at         = now()
WHERE id = $1
RETURNING id, endorser_id, endorsee_id, kind, festival_id, body, skills, hidden_by_endorsee, moderation_status, created_at, updated_at
`

type SetEndorsementVisibilityParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	HiddenByEndorsee bool        `db:"hidden_by_endorsee" json:"hidden_by_endorsee"`
}

func (q *Queries) SetEndorsementVisibility(ctx context.Context, arg SetEndorsementVisibilityParams) (Endorsement, error) {
	row := q.db.QueryRow(ctx, setEndorsementVisibility, arg.ID, arg.HiddenByEndorsee)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.EndorserID,
		&i.EndorseeID,
		&i.Kind,
		&i.FestivalID,
		&i.Body,
		&i.Skills,
		&i.HiddenByEndorsee,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
