// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festivals.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFestival = `-- name: CreateFestival :one
INSERT INTO festivals (organiser_id, name, slug, description, location_label, start_date, end_date, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organiser_id, name, slug, description, location_label, start_date, end_date, status, deleted_at, created_at, updated_at
`

type CreateFestivalParams struct {
	OrganiserID   pgtype.UUID    `db:"organiser_id" json:"organiser_id"`
	Name          string         `db:"name" json:"name"`
	Slug          string         `db:"slug" json:"slug"`
	Description   string         `db:"description" json:"description"`
	LocationLabel string         `db:"location_label" json:"location_label"`
	StartDate     pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date    `db:"end_date" json:"end_date"`
	Status        FestivalStatus `db:"status" json:"status"`
}

func (q *Queries) CreateFestival(ctx context.Context, arg CreateFestivalParams) (Festival, error) {
	row := q.db.QueryRow(ctx, createFestival,
		arg.OrganiserID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LocationLabel,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LocationLabel,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFestivalByID = `-- name: GetFestivalByID :one
SELECT id, organiser_id, name, slug, description, location_label, start_date, end_date, status, deleted_at, created_at, updated_at FROM festivals WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFestivalByID(ctx context.Context, id pgtype.UUID) (Festival, error) {
	row := q.db.QueryRow(ctx, getFestivalByID, id)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LocationLabel,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFestivalBySlug = `-- name: GetFestivalBySlug :one
SELECT id, organiser_id, name, slug, description, location_label, start_date, end_date, status, deleted_at, created_at, updated_at FROM festivals WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFestivalBySlug(ctx context.Context, slug string) (Festival, error) {
	row := q.db.QueryRow(ctx, getFestivalBySlug, slug)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LocationLabel,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFestivalsByOrganiser = `-- name: ListFestivalsByOrganiser :many
SELECT id, organiser_id, name, slug, description, location_label, start_date, end_date, status, deleted_at, created_at, updated_at FROM festivals WHERE organiser_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListFestivalsByOrganiser(ctx context.Context, organiserID pgtype.UUID) ([]Festival, error) {
	rows, err := q.db.Query(ctx, listFestivalsByOrganiser, organiserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Festival
	for rows.Next() {
		var i Festival
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LocationLabel,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFestival = `-- name: SoftDeleteFestival :exec
UPDATE festivals SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFestival(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFestival, id)
	return err
}

const updateFestival = `-- name: UpdateFestival :one
UPDATE festivals
SET name           = $2,
    slug           = $3,
    description    = $4,
    location_label = $5,
    start_date     = $6,
    end_date       = $7,
    status         = $8,
    updated_at     = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organiser_id, name, slug, description, location_label, start_date, end_date, status, deleted_at, created_at, updated_at
`

type UpdateFestivalParams struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	Name          string         `db:"name" json:"name"`
	Slug          string         `db:"slug" json:"slug"`
	Description   string         `db:"description" json:"description"`
	LocationLabel string         `db:"location_label" json:"location_label"`
	StartDate     pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date    `db:"end_date" json:"end_date"`
	Status        FestivalStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateFestival(ctx context.Context, arg UpdateFestivalParams) (Festival, error) {
	row := q.db.QueryRow(ctx, updateFestival,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LocationLabel,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LocationLabel,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
