// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festival_artists.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFestivalArtist = `-- name: AddFestivalArtist :one
INSERT INTO festival_artists (festival_id, artist_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (festival_id, artist_id) DO UPDATE
    SET status = EXCLUDED.status, updated_at = now()
RETURNING festival_id, artist_id, status, pin_lat, pin_lng, w3w, created_at, updated_at
`

type AddFestivalArtistParams struct {
	FestivalID pgtype.UUID          `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID          `db:"artist_id" json:"artist_id"`
	Status     FestivalArtistStatus `db:"status" json:"status"`
}

func (q *Queries) AddFestivalArtist(ctx context.Context, arg AddFestivalArtistParams) (FestivalArtist, error) {
	row := q.db.QueryRow(ctx, addFestivalArtist, arg.FestivalID, arg.ArtistID, arg.Status)
	var i FestivalArtist
	err := row.Scan(
		&i.FestivalID,
		&i.ArtistID,
		&i.Status,
		&i.PinLat,
		&i.PinLng,
		&i.W3w,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFestivalMapPins = `-- name: GetFestivalMapPins :many
SELECT fa.festival_id,
       fa.artist_id,
       fa.pin_lat,
       fa.pin_lng,
       fa.w3w,
       ap.display_name
FROM festival_artists fa
JOIN artist_profiles ap ON ap.id = fa.artist_id
WHERE fa.festival_id = $1
  AND fa.status = 'accepted'
  AND fa.pin_lat IS NOT NULL
  AND fa.pin_lng IS NOT NULL
`

type GetFestivalMapPinsRow struct {
	FestivalID  pgtype.UUID    `db:"festival_id" json:"festival_id"`
	ArtistID    pgtype.UUID    `db:"artist_id" json:"artist_id"`
	PinLat      pgtype.Numeric `db:"pin_lat" json:"pin_lat"`
	PinLng      pgtype.Numeric `db:"pin_lng" json:"pin_lng"`
	W3w         *string        `db:"w3w" json:"w3w"`
	DisplayName string         `db:"display_name" json:"display_name"`
}

func (q *Queries) GetFestivalMapPins(ctx context.Context, festivalID pgtype.UUID) ([]GetFestivalMapPinsRow, error) {
	rows, err := q.db.Query(ctx, getFestivalMapPins, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFestivalMapPinsRow
	for rows.Next() {
		var i GetFestivalMapPinsRow
		if err := rows.Scan(
			&i.FestivalID,
			&i.ArtistID,
			&i.PinLat,
			&i.PinLng,
			&i.W3w,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
