// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festival_spots.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFestivalSpotArtist = `-- name: ClearFestivalSpotArtist :one
UPDATE festival_spots
SET artist_id  = NULL,
    updated_at = now()
WHERE id = $1 AND festival_id = $2
RETURNING id, festival_id, number, lat, lng, w3w, width_m, height_m, notes, artist_id, created_at, updated_at, mural_status
`

type ClearFestivalSpotArtistParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

func (q *Queries) ClearFestivalSpotArtist(ctx context.Context, arg ClearFestivalSpotArtistParams) (FestivalSpot, error) {
	row := q.db.QueryRow(ctx, clearFestivalSpotArtist, arg.ID, arg.FestivalID)
	var i FestivalSpot
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Number,
		&i.Lat,
		&i.Lng,
		&i.W3w,
		&i.WidthM,
		&i.HeightM,
		&i.Notes,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MuralStatus,
	)
	return i, err
}

const clearSpotAssignmentForArtist = `-- name: ClearSpotAssignmentForArtist :exec
UPDATE festival_spots
SET artist_id = NULL, updated_at = now()
WHERE festival_id = $1 AND artist_id = $2
`

type ClearSpotAssignmentForArtistParams struct {
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID `db:"artist_id" json:"artist_id"`
}

// Removes an artist from any spot they hold in this festival (the spot itself,
// with its location/dimensions/notes, is preserved). Called whenever an artist
// stops being a spot-eligible accept.
func (q *Queries) ClearSpotAssignmentForArtist(ctx context.Context, arg ClearSpotAssignmentForArtistParams) error {
	_, err := q.db.Exec(ctx, clearSpotAssignmentForArtist, arg.FestivalID, arg.ArtistID)
	return err
}

const createFestivalSpot = `-- name: CreateFestivalSpot :one
INSERT INTO festival_spots (festival_id, number, lat, lng, w3w, width_m, height_m, notes)
VALUES (
    $1,
    COALESCE((SELECT MAX(number) FROM festival_spots WHERE festival_id = $1), 0) + 1,
    $2, $3, $4, $5, $6, $7
)
RETURNING id, festival_id, number, lat, lng, w3w, width_m, height_m, notes, artist_id, created_at, updated_at, mural_status
`

type CreateFestivalSpotParams struct {
	FestivalID pgtype.UUID    `db:"festival_id" json:"festival_id"`
	Lat        pgtype.Numeric `db:"lat" json:"lat"`
	Lng        pgtype.Numeric `db:"lng" json:"lng"`
	W3w        *string        `db:"w3w" json:"w3w"`
	WidthM     pgtype.Numeric `db:"width_m" json:"width_m"`
	HeightM    pgtype.Numeric `db:"height_m" json:"height_m"`
	Notes      *string        `db:"notes" json:"notes"`
}

func (q *Queries) CreateFestivalSpot(ctx context.Context, arg CreateFestivalSpotParams) (FestivalSpot, error) {
	row := q.db.QueryRow(ctx, createFestivalSpot,
		arg.FestivalID,
		arg.Lat,
		arg.Lng,
		arg.W3w,
		arg.WidthM,
		arg.HeightM,
		arg.Notes,
	)
	var i FestivalSpot
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Number,
		&i.Lat,
		&i.Lng,
		&i.W3w,
		&i.WidthM,
		&i.HeightM,
		&i.Notes,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MuralStatus,
	)
	return i, err
}

const deleteFestivalSpot = `-- name: DeleteFestivalSpot :exec
DELETE FROM festival_spots WHERE id = $1 AND festival_id = $2
`

type DeleteFestivalSpotParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

func (q *Queries) DeleteFestivalSpot(ctx context.Context, arg DeleteFestivalSpotParams) error {
	_, err := q.db.Exec(ctx, deleteFestivalSpot, arg.ID, arg.FestivalID)
	return err
}

const getFestivalMapPins = `-- name: GetFestivalMapPins :many
SELECT fs.festival_id,
       fs.artist_id,
       fs.lat      AS pin_lat,
       fs.lng      AS pin_lng,
       fs.w3w,
       ap.display_name
FROM festival_spots fs
JOIN artist_profiles ap ON ap.id = fs.artist_id
WHERE fs.festival_id = $1
  AND fs.artist_id IS NOT NULL
`

type GetFestivalMapPinsRow struct {
	FestivalID  pgtype.UUID    `db:"festival_id" json:"festival_id"`
	ArtistID    pgtype.UUID    `db:"artist_id" json:"artist_id"`
	PinLat      pgtype.Numeric `db:"pin_lat" json:"pin_lat"`
	PinLng      pgtype.Numeric `db:"pin_lng" json:"pin_lng"`
	W3w         *string        `db:"w3w" json:"w3w"`
	DisplayName string         `db:"display_name" json:"display_name"`
}

func (q *Queries) GetFestivalMapPins(ctx context.Context, festivalID pgtype.UUID) ([]GetFestivalMapPinsRow, error) {
	rows, err := q.db.Query(ctx, getFestivalMapPins, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFestivalMapPinsRow
	for rows.Next() {
		var i GetFestivalMapPinsRow
		if err := rows.Scan(
			&i.FestivalID,
			&i.ArtistID,
			&i.PinLat,
			&i.PinLng,
			&i.W3w,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFestivalSpot = `-- name: GetFestivalSpot :one
SELECT fs.id,
       fs.festival_id,
       fs.number,
       fs.lat,
       fs.lng,
       fs.w3w,
       fs.width_m,
       fs.height_m,
       fs.notes,
       fs.artist_id,
       fs.created_at,
       fs.updated_at,
       ap.display_name AS artist_name
FROM festival_spots fs
LEFT JOIN artist_profiles ap ON ap.id = fs.artist_id
WHERE fs.id = $1 AND fs.festival_id = $2
`

type GetFestivalSpotParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

type GetFestivalSpotRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	FestivalID pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Number     int32              `db:"number" json:"number"`
	Lat        pgtype.Numeric     `db:"lat" json:"lat"`
	Lng        pgtype.Numeric     `db:"lng" json:"lng"`
	W3w        *string            `db:"w3w" json:"w3w"`
	WidthM     pgtype.Numeric     `db:"width_m" json:"width_m"`
	HeightM    pgtype.Numeric     `db:"height_m" json:"height_m"`
	Notes      *string            `db:"notes" json:"notes"`
	ArtistID   pgtype.UUID        `db:"artist_id" json:"artist_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ArtistName *string            `db:"artist_name" json:"artist_name"`
}

func (q *Queries) GetFestivalSpot(ctx context.Context, arg GetFestivalSpotParams) (GetFestivalSpotRow, error) {
	row := q.db.QueryRow(ctx, getFestivalSpot, arg.ID, arg.FestivalID)
	var i GetFestivalSpotRow
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Number,
		&i.Lat,
		&i.Lng,
		&i.W3w,
		&i.WidthM,
		&i.HeightM,
		&i.Notes,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistName,
	)
	return i, err
}

const getFestivalSpots = `-- name: GetFestivalSpots :many
SELECT fs.id,
       fs.festival_id,
       fs.number,
       fs.lat,
       fs.lng,
       fs.w3w,
       fs.width_m,
       fs.height_m,
       fs.notes,
       fs.artist_id,
       fs.created_at,
       fs.updated_at,
       ap.display_name AS artist_name
FROM festival_spots fs
LEFT JOIN artist_profiles ap ON ap.id = fs.artist_id
WHERE fs.festival_id = $1
ORDER BY fs.number
`

type GetFestivalSpotsRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	FestivalID pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Number     int32              `db:"number" json:"number"`
	Lat        pgtype.Numeric     `db:"lat" json:"lat"`
	Lng        pgtype.Numeric     `db:"lng" json:"lng"`
	W3w        *string            `db:"w3w" json:"w3w"`
	WidthM     pgtype.Numeric     `db:"width_m" json:"width_m"`
	HeightM    pgtype.Numeric     `db:"height_m" json:"height_m"`
	Notes      *string            `db:"notes" json:"notes"`
	ArtistID   pgtype.UUID        `db:"artist_id" json:"artist_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ArtistName *string            `db:"artist_name" json:"artist_name"`
}

func (q *Queries) GetFestivalSpots(ctx context.Context, festivalID pgtype.UUID) ([]GetFestivalSpotsRow, error) {
	rows, err := q.db.Query(ctx, getFestivalSpots, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFestivalSpotsRow
	for rows.Next() {
		var i GetFestivalSpotsRow
		if err := rows.Scan(
			&i.ID,
			&i.FestivalID,
			&i.Number,
			&i.Lat,
			&i.Lng,
			&i.W3w,
			&i.WidthM,
			&i.HeightM,
			&i.Notes,
			&i.ArtistID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnassignedAcceptedArtists = `-- name: GetUnassignedAcceptedArtists :many
SELECT fa.artist_id, ap.display_name AS name
FROM festival_artists fa
JOIN artist_profiles ap ON ap.id = fa.artist_id
WHERE fa.festival_id = $1
  AND fa.status = 'accepted'
  AND NOT EXISTS (
    SELECT 1 FROM festival_spots fs
    WHERE fs.festival_id = $1 AND fs.artist_id = fa.artist_id
  )
ORDER BY ap.display_name
`

type GetUnassignedAcceptedArtistsRow struct {
	ArtistID pgtype.UUID `db:"artist_id" json:"artist_id"`
	Name     string      `db:"name" json:"name"`
}

func (q *Queries) GetUnassignedAcceptedArtists(ctx context.Context, festivalID pgtype.UUID) ([]GetUnassignedAcceptedArtistsRow, error) {
	rows, err := q.db.Query(ctx, getUnassignedAcceptedArtists, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnassignedAcceptedArtistsRow
	for rows.Next() {
		var i GetUnassignedAcceptedArtistsRow
		if err := rows.Scan(&i.ArtistID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnassignedSpotEligibleArtists = `-- name: GetUnassignedSpotEligibleArtists :many
SELECT elig.artist_id, elig.name
FROM (
    SELECT fa.artist_id, ap.display_name AS name
    FROM festival_artists fa
    JOIN artist_profiles ap ON ap.id = fa.artist_id
    WHERE fa.festival_id = $1 AND fa.status = 'accepted'
    UNION
    SELECT a.artist_id, ap.display_name AS name
    FROM applications a
    JOIN application_forms af ON af.id = a.form_id
    JOIN artist_profiles ap ON ap.id = a.artist_id
    WHERE af.festival_id = $1 AND a.staged_decision = 'accept'
) elig
WHERE NOT EXISTS (
    SELECT 1 FROM festival_spots fs
    WHERE fs.festival_id = $1 AND fs.artist_id = elig.artist_id
)
ORDER BY elig.name
`

type GetUnassignedSpotEligibleArtistsRow struct {
	ArtistID pgtype.UUID `db:"artist_id" json:"artist_id"`
	Name     string      `db:"name" json:"name"`
}

// Artists eligible to be placed on a spot: released accepts (festival_artists) OR
// provisional accepts (applications.staged_decision = 'accept'), minus those already
// assigned a spot. Feeds the map editor pool and the dashboard summary.
func (q *Queries) GetUnassignedSpotEligibleArtists(ctx context.Context, festivalID pgtype.UUID) ([]GetUnassignedSpotEligibleArtistsRow, error) {
	rows, err := q.db.Query(ctx, getUnassignedSpotEligibleArtists, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnassignedSpotEligibleArtistsRow
	for rows.Next() {
		var i GetUnassignedSpotEligibleArtistsRow
		if err := rows.Scan(&i.ArtistID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFestivalSpotArtist = `-- name: SetFestivalSpotArtist :one
UPDATE festival_spots
SET artist_id  = $3,
    updated_at = now()
WHERE id = $1 AND festival_id = $2
RETURNING id, festival_id, number, lat, lng, w3w, width_m, height_m, notes, artist_id, created_at, updated_at, mural_status
`

type SetFestivalSpotArtistParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID `db:"artist_id" json:"artist_id"`
}

func (q *Queries) SetFestivalSpotArtist(ctx context.Context, arg SetFestivalSpotArtistParams) (FestivalSpot, error) {
	row := q.db.QueryRow(ctx, setFestivalSpotArtist, arg.ID, arg.FestivalID, arg.ArtistID)
	var i FestivalSpot
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Number,
		&i.Lat,
		&i.Lng,
		&i.W3w,
		&i.WidthM,
		&i.HeightM,
		&i.Notes,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MuralStatus,
	)
	return i, err
}

const updateFestivalSpot = `-- name: UpdateFestivalSpot :one
UPDATE festival_spots
SET lat        = $3,
    lng        = $4,
    w3w        = $5,
    width_m    = $6,
    height_m   = $7,
    notes      = $8,
    updated_at = now()
WHERE id = $1 AND festival_id = $2
RETURNING id, festival_id, number, lat, lng, w3w, width_m, height_m, notes, artist_id, created_at, updated_at, mural_status
`

type UpdateFestivalSpotParams struct {
	ID         pgtype.UUID    `db:"id" json:"id"`
	FestivalID pgtype.UUID    `db:"festival_id" json:"festival_id"`
	Lat        pgtype.Numeric `db:"lat" json:"lat"`
	Lng        pgtype.Numeric `db:"lng" json:"lng"`
	W3w        *string        `db:"w3w" json:"w3w"`
	WidthM     pgtype.Numeric `db:"width_m" json:"width_m"`
	HeightM    pgtype.Numeric `db:"height_m" json:"height_m"`
	Notes      *string        `db:"notes" json:"notes"`
}

func (q *Queries) UpdateFestivalSpot(ctx context.Context, arg UpdateFestivalSpotParams) (FestivalSpot, error) {
	row := q.db.QueryRow(ctx, updateFestivalSpot,
		arg.ID,
		arg.FestivalID,
		arg.Lat,
		arg.Lng,
		arg.W3w,
		arg.WidthM,
		arg.HeightM,
		arg.Notes,
	)
	var i FestivalSpot
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.Number,
		&i.Lat,
		&i.Lng,
		&i.W3w,
		&i.WidthM,
		&i.HeightM,
		&i.Notes,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MuralStatus,
	)
	return i, err
}
