// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festival_artists.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFestivalArtist = `-- name: AddFestivalArtist :one
INSERT INTO festival_artists (festival_id, artist_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (festival_id, artist_id) DO UPDATE
    SET status = EXCLUDED.status, updated_at = now()
RETURNING festival_id, artist_id, status, created_at, updated_at
`

type AddFestivalArtistParams struct {
	FestivalID pgtype.UUID          `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID          `db:"artist_id" json:"artist_id"`
	Status     FestivalArtistStatus `db:"status" json:"status"`
}

func (q *Queries) AddFestivalArtist(ctx context.Context, arg AddFestivalArtistParams) (FestivalArtist, error) {
	row := q.db.QueryRow(ctx, addFestivalArtist, arg.FestivalID, arg.ArtistID, arg.Status)
	var i FestivalArtist
	err := row.Scan(
		&i.FestivalID,
		&i.ArtistID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcceptedArtistForFestival = `-- name: GetAcceptedArtistForFestival :one
SELECT fa.festival_id,
       fa.artist_id,
       ap.display_name
FROM festival_artists fa
JOIN artist_profiles ap ON ap.id = fa.artist_id
WHERE fa.festival_id = $1
  AND fa.artist_id = $2
  AND fa.status = 'accepted'
`

type GetAcceptedArtistForFestivalParams struct {
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID `db:"artist_id" json:"artist_id"`
}

type GetAcceptedArtistForFestivalRow struct {
	FestivalID  pgtype.UUID `db:"festival_id" json:"festival_id"`
	ArtistID    pgtype.UUID `db:"artist_id" json:"artist_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) GetAcceptedArtistForFestival(ctx context.Context, arg GetAcceptedArtistForFestivalParams) (GetAcceptedArtistForFestivalRow, error) {
	row := q.db.QueryRow(ctx, getAcceptedArtistForFestival, arg.FestivalID, arg.ArtistID)
	var i GetAcceptedArtistForFestivalRow
	err := row.Scan(&i.FestivalID, &i.ArtistID, &i.DisplayName)
	return i, err
}
