// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festival_reviewers.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFestivalReviewer = `-- name: AddFestivalReviewer :one
INSERT INTO festival_reviewers (festival_id, user_id)
VALUES ($1, $2)
ON CONFLICT (festival_id, user_id) DO UPDATE SET festival_id = EXCLUDED.festival_id
RETURNING festival_id, user_id, accepted_at, created_at
`

type AddFestivalReviewerParams struct {
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) AddFestivalReviewer(ctx context.Context, arg AddFestivalReviewerParams) (FestivalReviewer, error) {
	row := q.db.QueryRow(ctx, addFestivalReviewer, arg.FestivalID, arg.UserID)
	var i FestivalReviewer
	err := row.Scan(
		&i.FestivalID,
		&i.UserID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFestivalReviewer = `-- name: GetFestivalReviewer :one
SELECT festival_id, user_id, accepted_at, created_at FROM festival_reviewers WHERE festival_id = $1 AND user_id = $2
`

type GetFestivalReviewerParams struct {
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetFestivalReviewer(ctx context.Context, arg GetFestivalReviewerParams) (FestivalReviewer, error) {
	row := q.db.QueryRow(ctx, getFestivalReviewer, arg.FestivalID, arg.UserID)
	var i FestivalReviewer
	err := row.Scan(
		&i.FestivalID,
		&i.UserID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAcceptedFestivalReviewers = `-- name: ListAcceptedFestivalReviewers :many
SELECT fr.user_id, u.email, fr.accepted_at, fr.created_at
FROM festival_reviewers fr
JOIN users u ON u.id = fr.user_id
WHERE fr.festival_id = $1
  AND fr.accepted_at IS NOT NULL
ORDER BY fr.created_at ASC
`

type ListAcceptedFestivalReviewersRow struct {
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Email      string             `db:"email" json:"email"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListAcceptedFestivalReviewers(ctx context.Context, festivalID pgtype.UUID) ([]ListAcceptedFestivalReviewersRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedFestivalReviewers, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedFestivalReviewersRow
	for rows.Next() {
		var i ListAcceptedFestivalReviewersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFestivalReviewers = `-- name: ListFestivalReviewers :many
SELECT fr.festival_id, fr.user_id, fr.accepted_at, fr.created_at, u.email
FROM festival_reviewers fr
JOIN users u ON u.id = fr.user_id
WHERE fr.festival_id = $1
ORDER BY fr.created_at ASC
`

type ListFestivalReviewersRow struct {
	FestivalID pgtype.UUID        `db:"festival_id" json:"festival_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Email      string             `db:"email" json:"email"`
}

func (q *Queries) ListFestivalReviewers(ctx context.Context, festivalID pgtype.UUID) ([]ListFestivalReviewersRow, error) {
	rows, err := q.db.Query(ctx, listFestivalReviewers, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFestivalReviewersRow
	for rows.Next() {
		var i ListFestivalReviewersRow
		if err := rows.Scan(
			&i.FestivalID,
			&i.UserID,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFestivalsForReviewer = `-- name: ListFestivalsForReviewer :many
SELECT f.id, f.name, f.slug, f.status, f.start_date, f.end_date
FROM festival_reviewers fr
JOIN festivals f ON f.id = fr.festival_id
WHERE fr.user_id = $1 AND f.deleted_at IS NULL
ORDER BY f.created_at DESC
`

type ListFestivalsForReviewerRow struct {
	ID        pgtype.UUID    `db:"id" json:"id"`
	Name      string         `db:"name" json:"name"`
	Slug      string         `db:"slug" json:"slug"`
	Status    FestivalStatus `db:"status" json:"status"`
	StartDate pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date    `db:"end_date" json:"end_date"`
}

func (q *Queries) ListFestivalsForReviewer(ctx context.Context, userID pgtype.UUID) ([]ListFestivalsForReviewerRow, error) {
	rows, err := q.db.Query(ctx, listFestivalsForReviewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFestivalsForReviewerRow
	for rows.Next() {
		var i ListFestivalsForReviewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFestivalReviewer = `-- name: RemoveFestivalReviewer :exec
DELETE FROM festival_reviewers WHERE festival_id = $1 AND user_id = $2
`

type RemoveFestivalReviewerParams struct {
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveFestivalReviewer(ctx context.Context, arg RemoveFestivalReviewerParams) error {
	_, err := q.db.Exec(ctx, removeFestivalReviewer, arg.FestivalID, arg.UserID)
	return err
}
