// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festival_artists.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFestivalArtist = `-- name: AddFestivalArtist :one
INSERT INTO festival_artists (festival_id, artist_id, source)
VALUES ($1, $2, $3)
ON CONFLICT (festival_id, artist_id) DO UPDATE
    SET source = EXCLUDED.source, updated_at = now()
RETURNING festival_id, artist_id, source, created_at, updated_at
`

type AddFestivalArtistParams struct {
	FestivalID pgtype.UUID          `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID          `db:"artist_id" json:"artist_id"`
	Source     FestivalArtistSource `db:"source" json:"source"`
}

func (q *Queries) AddFestivalArtist(ctx context.Context, arg AddFestivalArtistParams) (FestivalArtist, error) {
	row := q.db.QueryRow(ctx, addFestivalArtist, arg.FestivalID, arg.ArtistID, arg.Source)
	var i FestivalArtist
	err := row.Scan(
		&i.FestivalID,
		&i.ArtistID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcceptedArtistForFestival = `-- name: GetAcceptedArtistForFestival :one
SELECT fa.festival_id,
       fa.artist_id,
       ap.display_name
FROM festival_artists fa
JOIN artist_profiles ap ON ap.id = fa.artist_id
WHERE fa.festival_id = $1
  AND fa.artist_id = $2
`

type GetAcceptedArtistForFestivalParams struct {
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID `db:"artist_id" json:"artist_id"`
}

type GetAcceptedArtistForFestivalRow struct {
	FestivalID  pgtype.UUID `db:"festival_id" json:"festival_id"`
	ArtistID    pgtype.UUID `db:"artist_id" json:"artist_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) GetAcceptedArtistForFestival(ctx context.Context, arg GetAcceptedArtistForFestivalParams) (GetAcceptedArtistForFestivalRow, error) {
	row := q.db.QueryRow(ctx, getAcceptedArtistForFestival, arg.FestivalID, arg.ArtistID)
	var i GetAcceptedArtistForFestivalRow
	err := row.Scan(&i.FestivalID, &i.ArtistID, &i.DisplayName)
	return i, err
}

const getSpotEligibleArtist = `-- name: GetSpotEligibleArtist :one
SELECT $1::uuid AS artist_id
WHERE EXISTS (
    SELECT 1 FROM festival_artists fa
    WHERE fa.festival_id = $2 AND fa.artist_id = $1
)
OR EXISTS (
    SELECT 1 FROM applications a
    JOIN application_forms af ON af.id = a.form_id
    WHERE af.festival_id = $2 AND a.artist_id = $1
      AND a.decision = 'accept' AND a.released_at IS NULL
)
`

type GetSpotEligibleArtistParams struct {
	ArtistID   pgtype.UUID `db:"artist_id" json:"artist_id"`
	FestivalID pgtype.UUID `db:"festival_id" json:"festival_id"`
}

// Returns the artist_id iff the artist is spot-eligible for this festival:
// a lineup member (festival_artists row) OR a provisional accept (decision = 'accept', not yet released).
// Used as the assignment guard in SetSpotArtistHandler. ErrNoRows => not eligible.
func (q *Queries) GetSpotEligibleArtist(ctx context.Context, arg GetSpotEligibleArtistParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSpotEligibleArtist, arg.ArtistID, arg.FestivalID)
	var artist_id pgtype.UUID
	err := row.Scan(&artist_id)
	return artist_id, err
}

const listPublicFestivalsForArtist = `-- name: ListPublicFestivalsForArtist :many
SELECT f.id,
       f.name,
       f.slug,
       f.start_date,
       f.end_date,
       f.status
FROM festivals f
WHERE f.deleted_at IS NULL
  AND f.status IN ('open', 'live')
  AND (
    EXISTS (
      SELECT 1 FROM festival_artists fa
      WHERE fa.festival_id = f.id
        AND fa.artist_id = $1
    )
    OR (f.status = 'live' AND EXISTS (
      SELECT 1 FROM festival_spots fs
      WHERE fs.festival_id = f.id
        AND fs.artist_id = $1
    ))
  )
ORDER BY f.start_date ASC NULLS LAST, f.created_at DESC
`

type ListPublicFestivalsForArtistRow struct {
	ID        pgtype.UUID    `db:"id" json:"id"`
	Name      string         `db:"name" json:"name"`
	Slug      string         `db:"slug" json:"slug"`
	StartDate pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date    `db:"end_date" json:"end_date"`
	Status    FestivalStatus `db:"status" json:"status"`
}

// Festivals where the given artist is a lineup member and/or has an assigned spot,
// restricted to festivals the public can see (open or live, not soft-deleted).
// Used by the public "Appearances" section on an artist profile.
func (q *Queries) ListPublicFestivalsForArtist(ctx context.Context, artistID pgtype.UUID) ([]ListPublicFestivalsForArtistRow, error) {
	rows, err := q.db.Query(ctx, listPublicFestivalsForArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicFestivalsForArtistRow
	for rows.Next() {
		var i ListPublicFestivalsForArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
