// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const healthCheck = `-- name: HealthCheck :one
SELECT applied_at FROM _migrations_health ORDER BY applied_at DESC LIMIT 1
`

func (q *Queries) HealthCheck(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var applied_at pgtype.Timestamptz
	err := row.Scan(&applied_at)
	return applied_at, err
}
