// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MigrationsHealth struct {
	AppliedAt pgtype.Timestamptz `db:"applied_at" json:"applied_at"`
}
