// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsEventType string

const (
	AnalyticsEventTypeProfileView AnalyticsEventType = "profile_view"
	AnalyticsEventTypeQrScan      AnalyticsEventType = "qr_scan"
	AnalyticsEventTypeLinkClick   AnalyticsEventType = "link_click"
)

func (e *AnalyticsEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticsEventType(s)
	case string:
		*e = AnalyticsEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticsEventType: %T", src)
	}
	return nil
}

type NullAnalyticsEventType struct {
	AnalyticsEventType AnalyticsEventType `json:"analytics_event_type"`
	Valid              bool               `json:"valid"` // Valid is true if AnalyticsEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticsEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticsEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticsEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticsEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticsEventType), nil
}

type ApplicationDecision string

const (
	ApplicationDecisionUndecided ApplicationDecision = "undecided"
	ApplicationDecisionAccept    ApplicationDecision = "accept"
	ApplicationDecisionWaitlist  ApplicationDecision = "waitlist"
	ApplicationDecisionDecline   ApplicationDecision = "decline"
)

func (e *ApplicationDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationDecision(s)
	case string:
		*e = ApplicationDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationDecision: %T", src)
	}
	return nil
}

type NullApplicationDecision struct {
	ApplicationDecision ApplicationDecision `json:"application_decision"`
	Valid               bool                `json:"valid"` // Valid is true if ApplicationDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationDecision) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationDecision), nil
}

type CollectionStatus string

const (
	CollectionStatusActive   CollectionStatus = "active"
	CollectionStatusArchived CollectionStatus = "archived"
	CollectionStatusOngoing  CollectionStatus = "ongoing"
)

func (e *CollectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionStatus(s)
	case string:
		*e = CollectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionStatus: %T", src)
	}
	return nil
}

type NullCollectionStatus struct {
	CollectionStatus CollectionStatus `json:"collection_status"`
	Valid            bool             `json:"valid"` // Valid is true if CollectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionStatus), nil
}

type FestivalArtistSource string

const (
	FestivalArtistSourceApplication FestivalArtistSource = "application"
	FestivalArtistSourceInvite      FestivalArtistSource = "invite"
)

func (e *FestivalArtistSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FestivalArtistSource(s)
	case string:
		*e = FestivalArtistSource(s)
	default:
		return fmt.Errorf("unsupported scan type for FestivalArtistSource: %T", src)
	}
	return nil
}

type NullFestivalArtistSource struct {
	FestivalArtistSource FestivalArtistSource `json:"festival_artist_source"`
	Valid                bool                 `json:"valid"` // Valid is true if FestivalArtistSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFestivalArtistSource) Scan(value interface{}) error {
	if value == nil {
		ns.FestivalArtistSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FestivalArtistSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFestivalArtistSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FestivalArtistSource), nil
}

type FestivalStatus string

const (
	FestivalStatusDraft    FestivalStatus = "draft"
	FestivalStatusOpen     FestivalStatus = "open"
	FestivalStatusLive     FestivalStatus = "live"
	FestivalStatusClosed   FestivalStatus = "closed"
	FestivalStatusArchived FestivalStatus = "archived"
)

func (e *FestivalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FestivalStatus(s)
	case string:
		*e = FestivalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FestivalStatus: %T", src)
	}
	return nil
}

type NullFestivalStatus struct {
	FestivalStatus FestivalStatus `json:"festival_status"`
	Valid          bool           `json:"valid"` // Valid is true if FestivalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFestivalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FestivalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FestivalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFestivalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FestivalStatus), nil
}

type AccessGrant struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Plan        string             `db:"plan" json:"plan"`
	FestivalID  pgtype.UUID        `db:"festival_id" json:"festival_id"`
	ValidUntil  pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
	GrantedBy   pgtype.UUID        `db:"granted_by" json:"granted_by"`
	PromoCodeID pgtype.UUID        `db:"promo_code_id" json:"promo_code_id"`
	Note        *string            `db:"note" json:"note"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AnalyticsEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	EventType  AnalyticsEventType `db:"event_type" json:"event_type"`
	ProfileID  pgtype.UUID        `db:"profile_id" json:"profile_id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

type Application struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	FormID      pgtype.UUID         `db:"form_id" json:"form_id"`
	ArtistID    pgtype.UUID         `db:"artist_id" json:"artist_id"`
	Answers     json.RawMessage     `db:"answers" json:"answers"`
	CreatedAt   pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	Rank        int32               `db:"rank" json:"rank"`
	Shortlisted bool                `db:"shortlisted" json:"shortlisted"`
	ReviewFlag  bool                `db:"review_flag" json:"review_flag"`
	Decision    ApplicationDecision `db:"decision" json:"decision"`
	ReleasedAt  pgtype.Timestamptz  `db:"released_at" json:"released_at"`
}

type ApplicationForm struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	FestivalID      pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Fields          json.RawMessage    `db:"fields" json:"fields"`
	OpenAt          pgtype.Timestamptz `db:"open_at" json:"open_at"`
	CloseAt         pgtype.Timestamptz `db:"close_at" json:"close_at"`
	MaxApplications *int32             `db:"max_applications" json:"max_applications"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ReviewCriteria  json.RawMessage    `db:"review_criteria" json:"review_criteria"`
}

type ApplicationNote struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	Content       string             `db:"content" json:"content"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AuthorID      pgtype.UUID        `db:"author_id" json:"author_id"`
}

type ApplicationScore struct {
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	ReviewerID    pgtype.UUID        `db:"reviewer_id" json:"reviewer_id"`
	Score         int32              `db:"score" json:"score"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CriterionID   string             `db:"criterion_id" json:"criterion_id"`
}

type ArtistProfile struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Bio                   string             `db:"bio" json:"bio"`
	LocationLabel         *string            `db:"location_label" json:"location_label"`
	ShowLocation          bool               `db:"show_location" json:"show_location"`
	MediumTags            []string           `db:"medium_tags" json:"medium_tags"`
	SocialLinks           json.RawMessage    `db:"social_links" json:"social_links"`
	AvatarS3Key           *string            `db:"avatar_s3_key" json:"avatar_s3_key"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	HeadlineImageUrls     []string           `db:"headline_image_urls" json:"headline_image_urls"`
	Visibility            string             `db:"visibility" json:"visibility"`
	PreviewToken          string             `db:"preview_token" json:"preview_token"`
	ClaimToken            *string            `db:"claim_token" json:"claim_token"`
	ClaimedAt             pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
	CreatedBy             pgtype.UUID        `db:"created_by" json:"created_by"`
	SupportUrl            *string            `db:"support_url" json:"support_url"`
	SetupCompletedAt      pgtype.Timestamptz `db:"setup_completed_at" json:"setup_completed_at"`
	HasUnpublishedChanges bool               `db:"has_unpublished_changes" json:"has_unpublished_changes"`
}

type BetaFeedback struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Kind      string             `db:"kind" json:"kind"`
	Body      string             `db:"body" json:"body"`
	AdminNote *string            `db:"admin_note" json:"admin_note"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BetaInvite struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	CreatedBy pgtype.UUID        `db:"created_by" json:"created_by"`
	MaxUses   int32              `db:"max_uses" json:"max_uses"`
	UsedCount int32              `db:"used_count" json:"used_count"`
	Cohort    string             `db:"cohort" json:"cohort"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Collection struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ArtistProfileID pgtype.UUID        `db:"artist_profile_id" json:"artist_profile_id"`
	Name            string             `db:"name" json:"name"`
	Description     string             `db:"description" json:"description"`
	CoverS3Key      *string            `db:"cover_s3_key" json:"cover_s3_key"`
	Status          CollectionStatus   `db:"status" json:"status"`
	DisplayOrder    int32              `db:"display_order" json:"display_order"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CoverFocalX     float32            `db:"cover_focal_x" json:"cover_focal_x"`
	CoverFocalY     float32            `db:"cover_focal_y" json:"cover_focal_y"`
}

type CollectionImage struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CollectionID pgtype.UUID        `db:"collection_id" json:"collection_id"`
	S3Key        string             `db:"s3_key" json:"s3_key"`
	CdnUrl       string             `db:"cdn_url" json:"cdn_url"`
	DisplayOrder int32              `db:"display_order" json:"display_order"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Endorsement struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	EndorserID       pgtype.UUID        `db:"endorser_id" json:"endorser_id"`
	EndorseeID       pgtype.UUID        `db:"endorsee_id" json:"endorsee_id"`
	Kind             string             `db:"kind" json:"kind"`
	FestivalID       pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Body             *string            `db:"body" json:"body"`
	Skills           []string           `db:"skills" json:"skills"`
	HiddenByEndorsee bool               `db:"hidden_by_endorsee" json:"hidden_by_endorsee"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Festival struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OrganiserID    pgtype.UUID        `db:"organiser_id" json:"organiser_id"`
	Name           string             `db:"name" json:"name"`
	Slug           string             `db:"slug" json:"slug"`
	Description    string             `db:"description" json:"description"`
	LocationLabel  string             `db:"location_label" json:"location_label"`
	StartDate      pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date        `db:"end_date" json:"end_date"`
	Status         FestivalStatus     `db:"status" json:"status"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ReviewOpenedAt pgtype.Timestamptz `db:"review_opened_at" json:"review_opened_at"`
	ReviewClosedAt pgtype.Timestamptz `db:"review_closed_at" json:"review_closed_at"`
	CenterLat      pgtype.Numeric     `db:"center_lat" json:"center_lat"`
	CenterLng      pgtype.Numeric     `db:"center_lng" json:"center_lng"`
}

type FestivalArtist struct {
	FestivalID pgtype.UUID          `db:"festival_id" json:"festival_id"`
	ArtistID   pgtype.UUID          `db:"artist_id" json:"artist_id"`
	Source     FestivalArtistSource `db:"source" json:"source"`
	CreatedAt  pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
}

type FestivalReviewer struct {
	FestivalID pgtype.UUID        `db:"festival_id" json:"festival_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FestivalSpot struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	FestivalID  pgtype.UUID        `db:"festival_id" json:"festival_id"`
	Number      int32              `db:"number" json:"number"`
	Lat         pgtype.Numeric     `db:"lat" json:"lat"`
	Lng         pgtype.Numeric     `db:"lng" json:"lng"`
	W3w         *string            `db:"w3w" json:"w3w"`
	WidthM      pgtype.Numeric     `db:"width_m" json:"width_m"`
	HeightM     pgtype.Numeric     `db:"height_m" json:"height_m"`
	Notes       *string            `db:"notes" json:"notes"`
	ArtistID    pgtype.UUID        `db:"artist_id" json:"artist_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MuralStatus string             `db:"mural_status" json:"mural_status"`
}

type MigrationsHealth struct {
	AppliedAt pgtype.Timestamptz `db:"applied_at" json:"applied_at"`
}

type OrganiserPayment struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	UserID                  pgtype.UUID        `db:"user_id" json:"user_id"`
	FestivalID              pgtype.UUID        `db:"festival_id" json:"festival_id"`
	StripeCheckoutSessionID *string            `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	StripePaymentIntentID   *string            `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	ChargeType              string             `db:"charge_type" json:"charge_type"`
	AmountPence             int32              `db:"amount_pence" json:"amount_pence"`
	Status                  string             `db:"status" json:"status"`
	PaidAt                  pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProfileSnapshot struct {
	ArtistProfileID pgtype.UUID        `db:"artist_profile_id" json:"artist_profile_id"`
	Snapshot        json.RawMessage    `db:"snapshot" json:"snapshot"`
	PublishedAt     pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type PromoCode struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Plan         string             `db:"plan" json:"plan"`
	DurationDays int32              `db:"duration_days" json:"duration_days"`
	MaxUses      *int32             `db:"max_uses" json:"max_uses"`
	UseCount     int32              `db:"use_count" json:"use_count"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy    pgtype.UUID        `db:"created_by" json:"created_by"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Subscription struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	FestivalID           pgtype.UUID        `db:"festival_id" json:"festival_id"`
	StripeSubscriptionID *string            `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	StripePriceID        string             `db:"stripe_price_id" json:"stripe_price_id"`
	Plan                 string             `db:"plan" json:"plan"`
	BillingInterval      string             `db:"billing_interval" json:"billing_interval"`
	Status               string             `db:"status" json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Email            string             `db:"email" json:"email"`
	PasswordHash     *string            `db:"password_hash" json:"password_hash"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	OauthProvider    *string            `db:"oauth_provider" json:"oauth_provider"`
	OauthSubject     *string            `db:"oauth_subject" json:"oauth_subject"`
	MfaEnabled       bool               `db:"mfa_enabled" json:"mfa_enabled"`
	MfaSecret        *string            `db:"mfa_secret" json:"mfa_secret"`
	SessionVersion   int32              `db:"session_version" json:"session_version"`
	StripeCustomerID *string            `db:"stripe_customer_id" json:"stripe_customer_id"`
	IsAdmin          bool               `db:"is_admin" json:"is_admin"`
	IsBeta           bool               `db:"is_beta" json:"is_beta"`
	BetaCohort       *string            `db:"beta_cohort" json:"beta_cohort"`
	InvitedBy        pgtype.UUID        `db:"invited_by" json:"invited_by"`
	InvitedVia       pgtype.UUID        `db:"invited_via" json:"invited_via"`
	EmailVerified    bool               `db:"email_verified" json:"email_verified"`
}

type WaitlistRequest struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
