// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_snapshots.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearProfileChanges = `-- name: ClearProfileChanges :exec
UPDATE artist_profiles SET has_unpublished_changes = false WHERE id = $1
`

func (q *Queries) ClearProfileChanges(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProfileChanges, id)
	return err
}

const getProfileSnapshot = `-- name: GetProfileSnapshot :one
SELECT snapshot, published_at FROM profile_snapshots
WHERE artist_profile_id = $1
`

type GetProfileSnapshotRow struct {
	Snapshot    json.RawMessage    `db:"snapshot" json:"snapshot"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) GetProfileSnapshot(ctx context.Context, artistProfileID pgtype.UUID) (GetProfileSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getProfileSnapshot, artistProfileID)
	var i GetProfileSnapshotRow
	err := row.Scan(&i.Snapshot, &i.PublishedAt)
	return i, err
}

const upsertProfileSnapshot = `-- name: UpsertProfileSnapshot :exec
INSERT INTO profile_snapshots (artist_profile_id, snapshot, published_at)
VALUES ($1, $2, now())
ON CONFLICT (artist_profile_id)
DO UPDATE SET snapshot = EXCLUDED.snapshot, published_at = now()
`

type UpsertProfileSnapshotParams struct {
	ArtistProfileID pgtype.UUID     `db:"artist_profile_id" json:"artist_profile_id"`
	Snapshot        json.RawMessage `db:"snapshot" json:"snapshot"`
}

func (q *Queries) UpsertProfileSnapshot(ctx context.Context, arg UpsertProfileSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertProfileSnapshot, arg.ArtistProfileID, arg.Snapshot)
	return err
}
