// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, password_hash, oauth_provider, oauth_subject)
VALUES ($1, NULL, $2, $3)
ON CONFLICT (oauth_provider, oauth_subject) WHERE oauth_provider IS NOT NULL
DO UPDATE SET oauth_provider = EXCLUDED.oauth_provider
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

type CreateOAuthUserParams struct {
	Email         string  `db:"email" json:"email"`
	OauthProvider *string `db:"oauth_provider" json:"oauth_provider"`
	OauthSubject  *string `db:"oauth_subject" json:"oauth_subject"`
}

// Idempotent upsert keyed on (oauth_provider, oauth_subject). Two concurrent
// first-login callbacks for the same OAuth identity will both succeed; the
// second one returns the row inserted by the first (no unique-violation 500).
// The DO UPDATE clause is a no-op write to make RETURNING * return a row.
func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser, arg.Email, arg.OauthProvider, arg.OauthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

type CreateUserParams struct {
	Email        string  `db:"email" json:"email"`
	PasswordHash *string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const disableMFA = `-- name: DisableMFA :one
UPDATE users
SET mfa_enabled = false, mfa_secret = NULL
WHERE id = $1
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

func (q *Queries) DisableMFA(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, disableMFA, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin FROM users
WHERE oauth_provider = $1 AND oauth_subject = $2
LIMIT 1
`

type GetUserByOAuthParams struct {
	OauthProvider *string `db:"oauth_provider" json:"oauth_provider"`
	OauthSubject  *string `db:"oauth_subject" json:"oauth_subject"`
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuth, arg.OauthProvider, arg.OauthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const incrementSessionVersion = `-- name: IncrementSessionVersion :one
UPDATE users
SET session_version = session_version + 1
WHERE id = $1
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

// Invalidates all outstanding JWTs for this user by bumping session_version.
// Called from the password-reset flow; the auth middleware compares the value
// baked into each JWT against this column and rejects any mismatch.
func (q *Queries) IncrementSessionVersion(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementSessionVersion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const linkOAuthToUser = `-- name: LinkOAuthToUser :one
UPDATE users
SET oauth_provider = $2, oauth_subject = $3
WHERE id = $1
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

type LinkOAuthToUserParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	OauthProvider *string     `db:"oauth_provider" json:"oauth_provider"`
	OauthSubject  *string     `db:"oauth_subject" json:"oauth_subject"`
}

func (q *Queries) LinkOAuthToUser(ctx context.Context, arg LinkOAuthToUserParams) (User, error) {
	row := q.db.QueryRow(ctx, linkOAuthToUser, arg.ID, arg.OauthProvider, arg.OauthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const setMFAEnabled = `-- name: SetMFAEnabled :one
UPDATE users
SET mfa_enabled = $2, mfa_secret = $3
WHERE id = $1
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

type SetMFAEnabledParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	MfaEnabled bool        `db:"mfa_enabled" json:"mfa_enabled"`
	MfaSecret  *string     `db:"mfa_secret" json:"mfa_secret"`
}

func (q *Queries) SetMFAEnabled(ctx context.Context, arg SetMFAEnabledParams) (User, error) {
	row := q.db.QueryRow(ctx, setMFAEnabled, arg.ID, arg.MfaEnabled, arg.MfaSecret)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, password_hash, created_at, oauth_provider, oauth_subject, mfa_enabled, mfa_secret, session_version, stripe_customer_id, is_admin
`

// Idempotent invite target. New rows are passwordless (valid for invitees /
// OAuth users). The no-op DO UPDATE makes RETURNING * yield the existing row.
func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.SessionVersion,
		&i.StripeCustomerID,
		&i.IsAdmin,
	)
	return i, err
}
