root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/bin/api"
  cmd = "go build -o ./tmp/bin/api ./cmd/api"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "0s"
  log = "air.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
