version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - noctx
    - sqlclosecheck

linters-settings:
  goimports:
    local-prefixes: github.com/sniffins-mcmuggins/render

issues:
  exclude-rules:
    # generated file
    - path: internal/openapi/api\.gen\.go
      linters: [all]
